# Generated by Django 5.1.4 on 2025-03-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qna',
            options={'permissions': [('manage', 'QNA 관리')]},
        ),
    ]
