# Generated by Django 5.1.4 on 2025-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_alter_qna_answer_alter_qna_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qna',
            name='question',
            field=models.TextField(),
        ),
    ]
