# Generated by Django 5.1.4 on 2025-05-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_qna_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
