# Generated by Django 5.1.4 on 2026-05-09 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deck', '0010_deck_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('venue', models.CharField(blank=True, default='', max_length=120)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('format', models.CharField(choices=[('swiss', '스위스'), ('elimination', '토너먼트'), ('hybrid', '스위스 + 토너먼트')], default='swiss', max_length=16)),
                ('status', models.CharField(choices=[('registration', '참가 접수'), ('running', '진행 중'), ('finished', '종료')], default='registration', max_length=16)),
                ('require_decklist', models.BooleanField(default=True)),
                ('round_duration_minutes', models.PositiveSmallIntegerField(default=50)),
                ('max_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=40)),
                ('seed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dropped', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_entries', to='deck.deck')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('stage', models.CharField(choices=[('swiss', '스위스'), ('elimination', '토너먼트')], default='swiss', max_length=16)),
                ('status', models.CharField(choices=[('running', '진행 중'), ('finished', '종료')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournament.tournament')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.PositiveSmallIntegerField()),
                ('is_draw', models.BooleanField(default=False)),
                ('player1_score', models.PositiveSmallIntegerField(default=0)),
                ('player2_score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '결과 대기'), ('reported', '결과 입력')], default='pending', max_length=16)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='tournament.tournamentparticipant')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='tournament.tournamentparticipant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournament.tournamentparticipant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournamentround')),
            ],
            options={
                'ordering': ['round__number', 'table_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipant',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='unique_tournament_user'),
        ),
        migrations.AddConstraint(
            model_name='tournamentround',
            constraint=models.UniqueConstraint(fields=('tournament', 'number'), name='unique_tournament_round_number'),
        ),
    ]
