# Generated by Django 5.1.4 on 2026-05-09 13:07

import django.db.models.deletion
from django.db import migrations, models


def migrate_decklist_required_count(apps, schema_editor):
    Tournament = apps.get_model('tournament', 'Tournament')
    for tournament in Tournament.objects.all():
        tournament.decklist_required_count = 1 if tournament.require_decklist else 0
        tournament.save(update_fields=['decklist_required_count'])


def migrate_existing_participant_decks(apps, schema_editor):
    TournamentParticipant = apps.get_model('tournament', 'TournamentParticipant')
    TournamentDeckSubmission = apps.get_model('tournament', 'TournamentDeckSubmission')
    for participant in TournamentParticipant.objects.exclude(deck_id__isnull=True):
        TournamentDeckSubmission.objects.get_or_create(
            participant_id=participant.id,
            slot=1,
            defaults={'deck_id': participant.deck_id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0010_deck_locked'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='decklist_required_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(migrate_decklist_required_count, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tournament',
            name='require_decklist',
        ),
        migrations.CreateModel(
            name='TournamentDeckSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_submissions', to='deck.deck')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_submissions', to='tournament.tournamentparticipant')),
            ],
            options={
                'ordering': ['slot'],
                'constraints': [models.UniqueConstraint(fields=('participant', 'slot'), name='unique_tournament_deck_submission_slot'), models.UniqueConstraint(fields=('participant', 'deck'), name='unique_tournament_deck_submission_deck')],
            },
        ),
        migrations.RunPython(migrate_existing_participant_decks, migrations.RunPython.noop),
    ]
