# Generated by Django 5.1.4 on 2026-05-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tournament_require_decklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='draw_points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='join_code',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='tournament',
            name='loss_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_set_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='visibility',
            field=models.CharField(choices=[('public', '공개'), ('unlisted', '일부 공개')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='tournament',
            name='win_points',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='draw_points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='loss_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='set_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='win_points',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
