# Generated by Django 5.1.4 on 2026-05-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_draw_points_tournament_join_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='swiss_round_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='top_cut_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
