# Generated by Django 5.1.4 on 2026-05-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_swiss_round_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker',
            field=models.CharField(choices=[('buchholz', 'Buchholz'), ('owm', 'OWM%')], default='buchholz', max_length=16),
        ),
    ]
