# Generated by Django 5.1.4 on 2026-05-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_tiebreaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='elimination_mode',
            field=models.CharField(choices=[('single', '싱글 엘리미네이션'), ('double', '더블 엘리미네이션')], default='single', max_length=16),
        ),
    ]
