# Generated by Django 5.1.4 on 2026-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_elimination_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
