# Generated by Django 5.1.4 on 2026-05-17 00:30

from django.db import migrations, models


def fill_double_elimination_brackets(apps, schema_editor):
    Tournament = apps.get_model('tournament', 'Tournament')
    TournamentMatch = apps.get_model('tournament', 'TournamentMatch')

    for tournament in Tournament.objects.filter(elimination_mode='double'):
        losses = {}
        matches = (
            TournamentMatch.objects.filter(
                round__tournament=tournament,
                round__stage='elimination',
            )
            .select_related('round')
            .order_by('round__number', 'table_no')
        )
        for match in matches:
            p1_losses = losses.get(match.player1_id, 0)
            p2_losses = losses.get(match.player2_id, 0) if match.player2_id else 0
            match.bracket = 'L' if p1_losses or p2_losses else 'W'
            match.save(update_fields=['bracket'])

            if match.status != 'reported' or not match.player2_id or not match.winner_id:
                continue
            if match.winner_id == match.player1_id:
                loser_id = match.player2_id
            elif match.winner_id == match.player2_id:
                loser_id = match.player1_id
            else:
                continue
            losses[loser_id] = losses.get(loser_id, 0) + 1


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_tournament_round_set_count_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='bracket',
            field=models.CharField(blank=True, choices=[('', '일반'), ('W', '승자조'), ('L', '패자조')], default='', max_length=1),
        ),
        migrations.RunPython(fill_double_elimination_brackets, migrations.RunPython.noop),
    ]
