# Generated by Django 5.1.4 on 2026-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournamentmatch_bracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='round_duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='set_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
