# Generated by Django 5.1.4 on 2025-04-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deck', '0006_alter_deckcomment_author_alter_deckcomment_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('datetime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=10)),
                ('user', models.CharField(blank=True, default='', max_length=30)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.championship')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.deck')),
            ],
        ),
        migrations.AddField(
            model_name='championship',
            name='decks',
            field=models.ManyToManyField(through='statistic.CSDeck', to='deck.deck'),
        ),
    ]
