# Generated by Django 5.1.4 on 2025-04-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0007_alter_deck_character'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='datetime',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='csdeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csdecks', to='deck.deck'),
        ),
    ]
