# Generated by Django 5.1.4 on 2025-05-16 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_csdeck_user_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='csdeck',
            name='user_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='css', to=settings.AUTH_USER_MODEL),
        ),
    ]
