# Generated by Django 5.1.4 on 2025-06-01 01:11

from django.db import migrations, models
import re

def copy_place_to_place_num(apps, schema_editor):
    CSDeck = apps.get_model('statistic', 'CSDeck')
    for obj in CSDeck.objects.all():
        m = re.search(r'\d+', obj.place or '')
        obj.place_num = int(m.group()) if m else None
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_alter_csdeck_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdeck',
            name='place_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.RunPython(copy_place_to_place_num),
    ]
