# Generated by Django 5.1.4 on 2025-06-01 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_csdeck_place_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csdeck',
            name='place',
        ),
    ]
