# Generated by Django 5.1.4 on 2026-05-13 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0023_card_detail_text'),
        ('tournament', '0007_tournament_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('standalone', '일반 계산기'), ('tournament', '대회 매치')], default='standalone', max_length=16)),
                ('view_token', models.CharField(max_length=64, unique=True)),
                ('control_token', models.CharField(max_length=64, unique=True)),
                ('player1_name', models.CharField(default='플레이어1', max_length=60)),
                ('player2_name', models.CharField(default='플레이어2', max_length=60)),
                ('player1_initial_hp', models.IntegerField(default=0)),
                ('player2_initial_hp', models.IntegerField(default=0)),
                ('player1_hp', models.IntegerField(default=0)),
                ('player2_hp', models.IntegerField(default=0)),
                ('player1_passive_state', models.JSONField(blank=True, default=dict)),
                ('player2_passive_state', models.JSONField(blank=True, default=dict)),
                ('timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('timer_duration_seconds', models.PositiveSmallIntegerField(default=10)),
                ('sudden_death', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_sessions', to=settings.AUTH_USER_MODEL)),
                ('player1_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_sessions_as_player1', to='card.character')),
                ('player2_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_sessions_as_player2', to='card.character')),
                ('tournament_match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_session', to='tournament.tournamentmatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='', max_length=80)),
                ('event_type', models.CharField(choices=[('hp', '체력 변경'), ('undo', '되돌리기'), ('timer', '타이머'), ('sudden_death', '서든 데스'), ('passive', '패시브 기록'), ('character', '캐릭터 선택')], max_length=24)),
                ('target', models.CharField(choices=[('p1', '플레이어1'), ('p2', '플레이어2'), ('global', '공통')], default='global', max_length=8)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('hp_before', models.IntegerField(blank=True, null=True)),
                ('hp_after', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_events', to=settings.AUTH_USER_MODEL)),
                ('undone_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undo_events', to='battlelog.battleevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='battlelog.battlesession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
