# Generated by Codex on 2026-05-13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlelog', '0005_tao_passive_harmony_reset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='battlesession',
            name='player1_fp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battlesession',
            name='player2_fp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battlesession',
            name='round_extra_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='event_type',
            field=models.CharField(choices=[('hp', '체력 변경'), ('fp', 'FP 변경'), ('undo', '되돌리기'), ('timer', '타이머'), ('sudden_death', '서든 데스'), ('passive', '패시브 기록'), ('character', '캐릭터 선택'), ('set_report', '세트 결과 보고'), ('set_start', '세트 시작'), ('extra_time', '추가 시간')], max_length=24),
        ),
        migrations.CreateModel(
            name='BattleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('running', '진행 중'), ('finished', '종료')], default='running', max_length=16)),
                ('winner_side', models.CharField(blank=True, choices=[('p1', '플레이어1'), ('p2', '플레이어2')], default='', max_length=8)),
                ('player1_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('player2_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('player1_start_hp', models.IntegerField(default=0)),
                ('player2_start_hp', models.IntegerField(default=0)),
                ('player1_start_fp', models.IntegerField(default=0)),
                ('player2_start_fp', models.IntegerField(default=0)),
                ('player1_end_hp', models.IntegerField(blank=True, null=True)),
                ('player2_end_hp', models.IntegerField(blank=True, null=True)),
                ('player1_end_fp', models.IntegerField(blank=True, null=True)),
                ('player2_end_fp', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('forced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_sets_forced', to=settings.AUTH_USER_MODEL)),
                ('player1_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_sets_confirmed_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_sets_confirmed_as_player2', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='battlelog.battlesession')),
            ],
            options={
                'ordering': ['set_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'set_number'), name='unique_battle_set_number')],
            },
        ),
    ]
