# Generated by Codex on 2026-05-13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlelog', '0006_battle_fp_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleevent',
            name='event_uid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='battleevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
