# Generated by Django 5.1.4 on 2026-08-17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlelog', '0022_delphy_garage_token_passive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesetRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, unique=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('source_manifest', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulator_ruleset_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'permissions': [('publish_ruleset', '자동 시뮬레이터 규칙 릴리스 게시')],
            },
        ),
        migrations.AddField(
            model_name='lumensimulatorsession',
            name='automation_failure',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lumensimulatorsession',
            name='mode',
            field=models.CharField(choices=[('manual', '수동'), ('automatic', '자동')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='lumensimulatorsession',
            name='ruleset_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulator_sessions', to='battlelog.rulesetrelease'),
        ),
    ]
