# Generated by Django 5.1.4 on 2026-08-18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlelog', '0023_automatic_rulesets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorAIPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lumen AI', max_length=80)),
                ('version', models.CharField(max_length=64, unique=True)),
                ('algorithm', models.CharField(choices=[('linear_v1', 'Linear policy v1')], default='linear_v1', max_length=32)),
                ('weights', models.JSONField(default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('training_games', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('train_ai_policy', '시뮬레이터 AI 정책 훈련')],
            },
        ),
        migrations.AddField(
            model_name='lumensimulatorsession',
            name='ai_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='battlelog.simulatoraipolicy'),
        ),
        migrations.AddField(
            model_name='lumensimulatorsession',
            name='player1_controller',
            field=models.CharField(choices=[('human', '사람'), ('ai', 'AI')], default='human', max_length=12),
        ),
        migrations.AddField(
            model_name='lumensimulatorsession',
            name='player2_controller',
            field=models.CharField(choices=[('human', '사람'), ('ai', 'AI')], default='human', max_length=12),
        ),
        migrations.CreateModel(
            name='AutomaticIssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origin', models.CharField(choices=[('engine', '자동 감지'), ('user', '사용자 제보')], max_length=12)),
                ('status', models.CharField(choices=[('open', '미해결'), ('resolved', '해결')], default='open', max_length=12)),
                ('error_type', models.CharField(blank=True, max_length=120)),
                ('summary', models.CharField(max_length=500)),
                ('diagnostic', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruleset_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_reports', to='battlelog.rulesetrelease')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_reports', to='battlelog.lumensimulatorsession')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='AutomaticIssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=12)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='battlelog.automaticissuereport')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatic_issue_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['created_at', 'id']},
        ),
    ]
