# Generated by Django 5.1.4 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('battlelog', '0028_seed_current_engine_ai_policy')]

    operations = [
        migrations.AlterField(
            model_name='automaticissuereport',
            name='origin',
            field=models.CharField(
                choices=[
                    ('engine', '엔진 자동 감지'),
                    ('client', '브라우저 자동 감지'),
                    ('user', '사용자 제보'),
                ],
                max_length=12,
            ),
        ),
    ]
