from copy import deepcopy
from functools import lru_cache

from django.db.utils import OperationalError, ProgrammingError

LANGUAGE_KOREAN = 'ko'
LANGUAGE_ENGLISH = 'en'
LANGUAGE_JAPANESE = 'ja'
DEFAULT_LANGUAGE = LANGUAGE_KOREAN
LANGUAGE_SESSION_KEY = 'lumengg_language'
LANGUAGE_COOKIE_NAME = 'lumengg_language'
LANGUAGE_COOKIE_MAX_AGE = 60 * 60 * 24 * 365

SUPPORTED_LANGUAGES = [
    (LANGUAGE_KOREAN, '한국어'),
    (LANGUAGE_ENGLISH, 'English'),
    (LANGUAGE_JAPANESE, '日本語'),
]
SUPPORTED_LANGUAGE_CODES = {code for code, _label in SUPPORTED_LANGUAGES}

UI_TRANSLATIONS = {
    LANGUAGE_ENGLISH: {
        '주 메뉴': 'Main menu',
        '카드': 'Cards',
        '캐릭터': 'Characters',
        '덱': 'Decks',
        '대회': 'Tournaments',
        '계산기': 'Calculator',
        '시뮬레이터': 'Simulator',
        '컬렉션': 'Collection',
        '로그인': 'Log in',
        '로그아웃': 'Log out',
        '라이트': 'Light',
        '다크': 'Dark',
        '테마로 변경': 'theme',
        '새 UI': 'New UI',
        '언어': 'Language',
        '루멘콘덴서 팬 사이트': 'LumenCondensor fan site',
        '본 사이트는 팬 사이트이며, 수익창출을 하지 않습니다.': 'This is a non-profit fan site.',
        '카드 검색': 'Card Search',
        '루멘콘덴서의 모든 카드를 검색할 수 있는 화면입니다.': 'Search every LumenCondensor card.',
        '총': 'Total',
        '장': ' cards',
        '명': ' characters',
        '페이지': 'page',
        '카드 추가': 'Add Card',
        '보충 설명 가져오기': 'Import Extra Notes',
        '필터': 'Filter',
        '검색': 'Search',
        '분류': 'Type',
        '판정': 'Hit Level',
        '부위': 'Property',
        '특수 판정': 'Special Judgment',
        '속도': 'Speed',
        '출신 팩': 'Pack',
        '관리': 'Admin',
        '태그 목록': 'Tag List',
        '태그 없음': 'No tags',
        '검색 결과가 없습니다.': 'No cards found.',
        '돌아가기': 'Back',
        '목록': 'List',
        '카드 수정': 'Edit Card',
        '평점': 'Rating',
        '채용률': 'Usage',
        '판본 변경': 'Change Print',
        '대미지': 'Damage',
        '효과': 'Effect',
        '+보충 설명': '+Extra Notes',
        '보충 설명': 'Extra Notes',
        '덱 채용률': 'Deck Usage',
        '태그': 'Tags',
        '출시일': 'Release Date',
        '수록번호': 'Collector Number',
        '수록 팩': 'Set',
        '레어도': 'Rarity',
        '수록 정보': 'Printings',
        '수록 정보가 없습니다.': 'No printing information.',
        '관련 카드': 'Related Cards',
        '관련 Q&A': 'Related Q&A',
        '태그 업데이트': 'Update Tags',
        '이 카드가 가진 태그': 'Tags on this card',
        '이 카드가 찾는 태그': 'Tags this card searches for',
        '숨겨진 검색어': 'Hidden search terms',
        '수정': 'Update',
        '미발매': 'Unreleased',
        '최초 수록': 'First Print',
        '없음': 'None',
        '정렬': 'Sort',
        '출시일 느린 순': 'Release Date Desc',
        '출시일 빠른 순': 'Release Date Asc',
        '속도 내림차순': 'Speed Desc',
        '속도 오름차순': 'Speed Asc',
        '데미지 내림차순': 'Damage Desc',
        '데미지 오름차순': 'Damage Asc',
        '히트 내림차순': 'Hit Desc',
        '히트 오름차순': 'Hit Asc',
        '카운터 내림차순': 'Counter Desc',
        '카운터 오름차순': 'Counter Asc',
        '가드 내림차순': 'Guard Desc',
        '가드 오름차순': 'Guard Asc',
        '평점 내림차순': 'Rating Desc',
        '평점 오름차순': 'Rating Asc',
        '일치': 'Exact',
        '이상': 'At least',
        '이하': 'At most',
        '카드명, 키워드 검색': 'Search card name or keyword',
        '캐릭터별 성향, 대표 카드, 코멘트를 한 화면에서 확인합니다.': 'View character traits, key cards, and comments.',
        '캐릭터 코멘트': 'Character Comments',
        '작성': 'Submit',
        '코멘트': 'Comment',
        '패시브': 'Passive',
        '스킨': 'Skin',
        '토큰': 'Token',
        '기타': 'Other',
        '그래프': 'Graph',
        '중요한 카드': 'Key Cards',
        '초반 심리전': 'Early mind games',
        '강력한 콤보용': 'Strong combo play',
        '압박 주축 카드': 'Core pressure card',
        '화력': 'Power',
        '연계': 'Combo',
        '변수창출': 'Reversal',
        '안정성': 'Safety',
        '변수': 'Rev.',
        '안정': 'Safe',
        '템포': 'Tempo',
        '미평가': 'Unrated',
        '데이터': 'Data',
        '공격력, 한 방의 위력과 평균적인 데미지 기대치': 'Attack power, single-hit impact, and average damage potential',
        '연속 공격이나 캐치, 콤보의 용이함/데미지': 'Ease and damage of chains, catches, and combos',
        '불리한 상황에서 역전할 수 있는 능력': 'Ability to turn around a bad situation',
        '플레이의 안정성, 리스크 관리 능력. 높을 수록 안정적임': 'Stability and risk management. Higher is safer.',
        '메인 플레이를 펼치기 위한 시간. 높을 수록 빠름을 의미': 'Time needed to reach the main game plan. Higher is faster.',
        '전체 덱': 'All decks',
    },
    LANGUAGE_JAPANESE: {
        '주 메뉴': 'メインメニュー',
        '카드': 'カード',
        '캐릭터': 'キャラクター',
        '덱': 'デッキ',
        '대회': '大会',
        '계산기': '計算機',
        '시뮬레이터': 'シミュレーター',
        '컬렉션': 'コレクション',
        '로그인': 'ログイン',
        '로그아웃': 'ログアウト',
        '라이트': 'ライト',
        '다크': 'ダーク',
        '테마로 변경': 'テーマに変更',
        '새 UI': '新UI',
        '언어': '言語',
        '루멘콘덴서 팬 사이트': 'ルーメンコンデンサー ファンサイト',
        '본 사이트는 팬 사이트이며, 수익창출을 하지 않습니다.': '本サイトは非営利のファンサイトです。',
        '카드 검색': 'カード検索',
        '루멘콘덴서의 모든 카드를 검색할 수 있는 화면입니다.': 'ルーメンコンデンサーのすべてのカードを検索できます。',
        '총': '全',
        '장': '枚',
        '명': '名',
        '페이지': 'ページ',
        '카드 추가': 'カード追加',
        '보충 설명 가져오기': '補足説明を取り込む',
        '필터': 'フィルター',
        '검색': '検索',
        '분류': '分類',
        '판정': '判定',
        '부위': '部位',
        '특수 판정': '特殊判定',
        '속도': '速度',
        '출신 팩': '収録パック',
        '관리': '管理',
        '태그 목록': 'タグ一覧',
        '태그 없음': 'タグなし',
        '검색 결과가 없습니다.': '検索結果がありません。',
        '돌아가기': '戻る',
        '목록': '一覧',
        '카드 수정': 'カード編集',
        '평점': '評価',
        '채용률': '採用率',
        '판본 변경': '版を変更',
        '대미지': 'ダメージ',
        '효과': '効果',
        '+보충 설명': '+補足説明',
        '보충 설명': '補足説明',
        '덱 채용률': 'デッキ採用率',
        '태그': 'タグ',
        '출시일': '発売日',
        '수록번호': '収録番号',
        '수록 팩': '収録パック',
        '레어도': 'レアリティ',
        '수록 정보': '収録情報',
        '수록 정보가 없습니다.': '収録情報がありません。',
        '관련 카드': '関連カード',
        '관련 Q&A': '関連Q&A',
        '태그 업데이트': 'タグ更新',
        '이 카드가 가진 태그': 'このカードのタグ',
        '이 카드가 찾는 태그': 'このカードが参照するタグ',
        '숨겨진 검색어': '隠し検索語',
        '수정': '修正',
        '미발매': '未発売',
        '최초 수록': '初収録',
        '없음': 'なし',
        '정렬': '並び替え',
        '출시일 느린 순': '発売日 降順',
        '출시일 빠른 순': '発売日 昇順',
        '속도 내림차순': '速度 降順',
        '속도 오름차순': '速度 昇順',
        '데미지 내림차순': 'ダメージ 降順',
        '데미지 오름차순': 'ダメージ 昇順',
        '히트 내림차순': 'ヒット 降順',
        '히트 오름차순': 'ヒット 昇順',
        '카운터 내림차순': 'カウンター 降順',
        '카운터 오름차순': 'カウンター 昇順',
        '가드 내림차순': 'ガード 降順',
        '가드 오름차순': 'ガード 昇順',
        '평점 내림차순': '評価 降順',
        '평점 오름차순': '評価 昇順',
        '일치': '一致',
        '이상': '以上',
        '이하': '以下',
        '카드명, 키워드 검색': 'カード名、キーワード検索',
        '캐릭터별 성향, 대표 카드, 코멘트를 한 화면에서 확인합니다.': 'キャラクターごとの傾向、代表カード、コメントを確認できます。',
        '캐릭터 코멘트': 'キャラクターコメント',
        '작성': '投稿',
        '코멘트': 'コメント',
        '패시브': 'パッシブ',
        '스킨': 'スキン',
        '토큰': 'トークン',
        '기타': 'その他',
        '그래프': 'グラフ',
        '중요한 카드': '重要カード',
        '초반 심리전': '序盤の読み合い',
        '강력한 콤보용': '強力なコンボ用',
        '압박 주축 카드': '攻めの主軸カード',
        '화력': '火力',
        '연계': '連携',
        '변수창출': '逆転力',
        '안정성': '安定性',
        '변수': '逆転',
        '안정': '安定',
        '템포': 'テンポ',
        '미평가': '未評価',
        '데이터': 'データ',
        '공격력, 한 방의 위력과 평균적인 데미지 기대치': '攻撃力、一撃の威力、平均ダメージ期待値',
        '연속 공격이나 캐치, 콤보의 용이함/데미지': '連続攻撃、キャッチ、コンボのしやすさとダメージ',
        '불리한 상황에서 역전할 수 있는 능력': '不利な状況を逆転する能力',
        '플레이의 안정성, 리스크 관리 능력. 높을 수록 안정적임': 'プレイの安定性とリスク管理能力。高いほど安定。',
        '메인 플레이를 펼치기 위한 시간. 높을 수록 빠름을 의미': '主軸の動きに入るまでの速さ。高いほど速い。',
        '전체 덱': '全デッキ',
    },
}

GAME_TERM_TRANSLATIONS = {
    LANGUAGE_ENGLISH: {
        '특성': 'Passive',
        '공격': 'Attack',
        '수비': 'Defense',
        '특수': 'Special',
        '토큰': 'Token',
        '얼티밋': 'Ultimate',
        '상단': 'High',
        '중단': 'Mid',
        '하단': 'Low',
        '상•중•하단 회피': 'High/Mid/Low Dodge',
        '상단·중단 상쇄': 'High/Mid Clash',
        '상단·중단 회피': 'High/Mid Dodge',
        '하단 회피/그랩': 'Low Dodge/Grab',
        '중단 산쇄': 'Mid Clash',
        '손': 'Hand',
        '발': 'Foot',
        '잔향': 'Echo',
        '방어': 'Guard',
        '회피': 'Dodge',
        '상쇄': 'Clash',
        '산쇄': 'Clash',
        '그랩': 'Grab',
        '판정': 'Judgment',
        '특수 판정': 'Special Judgment',
        '부위': 'Property',
        '속도': 'Speed',
        '대미지': 'Damage',
        '데미지': 'Damage',
        '이상': 'or higher',
        '이하': 'or lower',
        '초과': 'or higher',
        '미만': 'or lower',
        '없음': 'None',
        '히트': 'Hit',
        '가드': 'Guard',
        '카운터': 'Counter',
        '콤보': 'Combo',
        '브레이크': 'Break',
        '브레이크 불가': 'Cannot Break',
        '효과 대미지': 'Effect Damage',
        '효과 면역': 'Effect Immunity',
        '콤보 시동기': 'Combo Starter',
        '콤보 사용 불가': 'Cannot Combo',
        '콤보 변속': 'Combo Speed Shift',
        '속도 변경': 'Speed Change',
        '속도 고정': 'Speed Lock',
        '속도 무시': 'Ignore Speed',
        '기술 획득': 'Gain Technique',
        '회피 불가': 'Cannot Dodge',
        '상쇄 불가': 'Cannot Clash',
        '보정 무시': 'Ignore Scaling',
        '이득기': 'Advantage',
        '오버 리밋': 'Over Limit',
        '다운 스탠스': 'Down Stance',
        '차지': 'Charge',
        '위압': 'Intimidation',
        '조화': 'Harmony',
        '조화 상태': 'Harmony State',
        '조화 효과': 'Harmony Effect',
        '음': 'Yin',
        '양': 'Yang',
        '음 효과': 'Yin Effect',
        '양 효과': 'Yang Effect',
        '음 획득': 'Gain Yin',
        '양 획득': 'Gain Yang',
        '은연 획득': 'Gain Silver Bond',
        '은연 소모': 'Spend Silver Bond',
        '불씨 획득': 'Gain Ember',
        '불씨 소모': 'Spend Ember',
        '하울링': 'Howling',
        '암야': 'Dark Night',
        '암야 획득': 'Gain Dark Night',
        '예고': 'Notice',
        '개러지': 'Garage',
        '개러지 토큰': 'Garage Token',
        '에라타': 'Errata',
        '니아': 'Nia',
        '델피': 'Delphy',
        '레브': 'Rev',
        '루트': 'Root',
        '리타': 'Rita',
        '린': 'Rin',
        '무영': 'Muyeong',
        '비올라': 'Viola',
        '세츠메이': 'Setsumei',
        '요한': 'Johann',
        '울프': 'Wolf',
        '이오몽': 'Iomong',
        '이제벨': 'Izebel',
        '키메라': 'Chimera',
        '키스': 'Kiss',
        '타오': 'Tao',
        '핀프': 'Pinp',
        '루멘콘덴서': 'LumenCondensor',
        '뉴트럴': 'Neutral',
    },
    LANGUAGE_JAPANESE: {
        '특성': '特性',
        '공격': '攻撃',
        '수비': '防御',
        '특수': '特殊',
        '토큰': 'トークン',
        '얼티밋': 'アルティメット',
        '상단': '上段',
        '중단': '中段',
        '하단': '下段',
        '상•중•하단 회피': '上段/中段/下段 回避',
        '상단·중단 상쇄': '上段/中段 相殺',
        '상단·중단 회피': '上段/中段 回避',
        '하단 회피/그랩': '下段 回避/投げ',
        '중단 산쇄': '中段 相殺',
        '손': '手',
        '발': '足',
        '잔향': '残響',
        '방어': 'ガード',
        '회피': '回避',
        '상쇄': '相殺',
        '산쇄': '相殺',
        '그랩': '投げ',
        '판정': '判定',
        '특수 판정': '特殊判定',
        '부위': '部位',
        '속도': '速度',
        '대미지': 'ダメージ',
        '데미지': 'ダメージ',
        '이상': '以上',
        '이하': '以下',
        '초과': '超過',
        '미만': '未満',
        '없음': 'なし',
        '히트': 'ヒット',
        '가드': 'ガード',
        '카운터': 'カウンター',
        '콤보': 'コンボ',
        '브레이크': 'ブレイク',
        '브레이크 불가': 'ブレイク不可',
        '효과 대미지': '効果ダメージ',
        '효과 면역': '効果耐性',
        '콤보 시동기': 'コンボ始動',
        '콤보 사용 불가': 'コンボ使用不可',
        '콤보 변속': 'コンボ変速',
        '속도 변경': '速度変更',
        '속도 고정': '速度固定',
        '속도 무시': '速度無視',
        '기술 획득': '技獲得',
        '회피 불가': '回避不可',
        '상쇄 불가': '相殺不可',
        '보정 무시': '補正無視',
        '이득기': '有利技',
        '오버 리밋': 'オーバーリミット',
        '다운 스탠스': 'ダウンスタンス',
        '차지': 'チャージ',
        '위압': '威圧',
        '조화': '調和',
        '조화 상태': '調和状態',
        '조화 효과': '調和効果',
        '음': '陰',
        '양': '陽',
        '음 효과': '陰効果',
        '양 효과': '陽効果',
        '음 획득': '陰獲得',
        '양 획득': '陽獲得',
        '은연 획득': '銀縁獲得',
        '은연 소모': '銀縁消費',
        '불씨 획득': '火種獲得',
        '불씨 소모': '火種消費',
        '하울링': 'ハウリング',
        '암야': '闇夜',
        '암야 획득': '闇夜獲得',
        '예고': '予告',
        '개러지': 'ガレージ',
        '개러지 토큰': 'ガレージトークン',
        '에라타': 'エラッタ',
        '니아': 'ニア',
        '델피': 'デルフィ',
        '레브': 'レブ',
        '루트': 'ルート',
        '리타': 'リタ',
        '린': 'リン',
        '무영': 'ムヨン',
        '비올라': 'ヴィオラ',
        '세츠메이': 'セツメイ',
        '요한': 'ヨハン',
        '울프': 'ウルフ',
        '이오몽': 'イオモン',
        '이제벨': 'イゼベル',
        '키메라': 'キメラ',
        '키스': 'キス',
        '타오': 'タオ',
        '핀프': 'ピンプ',
        '루멘콘덴서': 'ルーメンコンデンサー',
        '뉴트럴': 'ニュートラル',
    },
}

PACK_TERM_TRANSLATIONS = {
    LANGUAGE_ENGLISH: {
        '스타터 덱': 'Starter Deck',
        '지식의 은묘 니아': 'Nia, Silver Cat of Knowledge',
        '뇌전의 헌터 루트': 'Root, Thunder Hunter',
        '열혈! 정비 소녀 델피': 'Delphy, Hot-Blooded Mechanic Girl',
        '괴도 키스 더 래빗': 'Kiss the Rabbit, Phantom Thief',
        '제국의 칼날 울프': 'Wolf, Blade of the Empire',
        '매혹의 무희 비올라': 'Viola, Enchanting Dancer',
        '어웨이크닝 루멘': 'Awakening Lumen',
        '유니즌 챌린저': 'Unison Challenger',
        '루미너스 이노센스': 'Luminous Innocence',
        '크림슨 스트라이커즈': 'Crimson Strikers',
        '프레데터 엠프레스': 'Predator Empress',
        '월야의 마당놀이': 'Moonlit Yard Game',
        '잔칫날의 초담': 'Chodam of the Feast Day',
        '리인포스드 소울즈': 'Reinforced Souls',
        '디파이언트 레조넌스': 'Defiant Resonance',
        '챔피언십 팩': 'Championship Pack',
        '프로모': 'Promo',
    },
    LANGUAGE_JAPANESE: {
        '스타터 덱': 'スターターデッキ',
        '지식의 은묘 니아': '知識の銀猫 ニア',
        '뇌전의 헌터 루트': '雷電のハンター ルート',
        '열혈! 정비 소녀 델피': '熱血！整備少女 デルフィ',
        '괴도 키스 더 래빗': '怪盗キス・ザ・ラビット',
        '제국의 칼날 울프': '帝国の刃 ウルフ',
        '매혹의 무희 비올라': '魅惑の舞姫 ヴィオラ',
        '어웨이크닝 루멘': 'アウェイクニングルーメン',
        '유니즌 챌린저': 'ユニゾンチャレンジャー',
        '루미너스 이노센스': 'ルミナスイノセンス',
        '크림슨 스트라이커즈': 'クリムゾンストライカーズ',
        '프레데터 엠프레스': 'プレデターエンプレス',
        '월야의 마당놀이': '月夜の庭遊び',
        '잔칫날의 초담': '祝宴の日のチョダム',
        '리인포스드 소울즈': 'リインフォースドソウルズ',
        '디파이언트 레조넌스': 'ディファイアントレゾナンス',
        '챔피언십 팩': 'チャンピオンシップパック',
        '프로모': 'プロモ',
    },
}

TOOL_UI_TRANSLATIONS = {
    LANGUAGE_ENGLISH: {
        '대전 계산기': 'Battle Calculator',
        '두 플레이어의 캐릭터를 선택해 체력, 손패 제한, 패시브 기록을 관리합니다.': 'Choose both characters and manage HP, hand limits, and passive notes.',
        '플레이어1 이름': 'Player 1 Name',
        '플레이어2 이름': 'Player 2 Name',
        '플레이어1 캐릭터': 'Player 1 Character',
        '플레이어2 캐릭터': 'Player 2 Character',
        '플레이어1 덱 ID': 'Player 1 Deck ID',
        '플레이어2 덱 ID': 'Player 2 Deck ID',
        '계산기 시작': 'Start Calculator',
        '플레이어1': 'Player 1',
        '플레이어2': 'Player 2',
        '로그 닫기': 'Close Log',
        '공유 닫기': 'Close Share',
        '링크 공유': 'Share Links',
        '관전 링크 복사': 'Copy Viewer Link',
        '조작 링크 복사': 'Copy Control Link',
        '관전 링크': 'Viewer Link',
        '조작 링크': 'Control Link',
        '닫기': 'Close',
        '초기화': 'Reset',
        '손패 -': 'Hand -',
        '손패': 'Hand',
        '대회 복귀': 'Back to Tournament',
        '게임 시간': 'Game Time',
        '서든 데스': 'Sudden Death',
        '서든 데스 해제': 'End Sudden Death',
        '10초 타이머': '10s Timer',
        '10초': '10s',
        '결과 보고': 'Report Result',
        '보고 완료': 'Reported',
        '되돌리기': 'Undo',
        '로그 확인': 'View Log',
        '전체화면': 'Fullscreen',
        '기록': 'Log',
        '전체': 'All',
        '선택': 'Select',
        '결과 확정': 'Confirm Result',
        '승으로 확정': 'wins',
        '추가 시간': 'Extra Time',
        '추가 턴 종료': 'End Extra Turn',
        '남은 추가 턴': 'Extra Turns Left',
        '턴': 'turns',
        '세트': 'Set',
        '세트 시작': 'Set Start',
        '세트 결과 확인': 'Set Result Confirmed',
        '체력 변경 되돌림': 'HP Change Undone',
        '10초 타이머 시작': '10s Timer Started',
        '10초 타이머 정지': '10s Timer Stopped',
        '서든 데스 진입': 'Sudden Death Started',
        '서든 데스 추가 턴 종료': 'Sudden Death Extra Turn Ended',
        '남은 턴': 'Turns Left',
        '패시브 패널 스크립트 오류가 발생했습니다.': 'Passive panel script error.',
        '캐릭터를 선택하면 패시브 패널이 표시됩니다.': 'Choose a character to show the passive panel.',
        '표시할 기록이 없습니다.': 'No records to show.',
        '계산기 연결이 끊겼습니다.': 'Calculator connection was lost.',
        '계산기 세션을 초기화할까요? 현재 HP, FP, 패시브, 타이머, 로그가 초기 상태로 돌아갑니다.': 'Reset this calculator session? Current HP, FP, passives, timer, and log will return to their initial state.',
        '일반 계산기 세션만 초기화할 수 있습니다.': 'Only standalone calculator sessions can be reset.',
        '서든 데스에 진입할까요? 각 플레이어의 HP는 1000, FP는 0이 되고 추가 턴 3턴이 시작됩니다.': 'Enter Sudden Death? Each player will be set to 1000 HP and 0 FP, and 3 extra turns will begin.',
        '서든 데스를 해제할까요?': 'End Sudden Death?',
        '루멘콘덴서 시뮬레이터': 'LumenCondensor Simulator',
        '모바일': 'Mobile',
        '모바일 시뮬레이터': 'Mobile Simulator',
        '데스크톱': 'Desktop',
        '접속': 'Role',
        '새로고침': 'Refresh',
        '카드가 없습니다.': 'No cards.',
        '시뮬레이터 가이드': 'Simulator Guide',
        '가이드': 'Guide',
        '루멘콘덴서 웹 시뮬레이터는 카드 효과를 자동 판정하지 않고, 두 플레이어가 같은 보드와 로그를 보며 진행을 맞추는 도구입니다.': 'The LumenCondensor web simulator does not automatically judge card effects. It lets both players share the same board and log while coordinating the game state.',
        '목차': 'Contents',
        '카드를 움직이는 법': 'Moving Cards',
        '행동 요청과 행동 완료': 'Action Requests and Completion',
        '패시브 효과': 'Passive Effects',
        '카드 효과': 'Card Effects',
        '카드 크기': 'Card Size',
        '카드 축소': 'Decrease Card Size',
        '카드 확대': 'Increase Card Size',
        '최소': 'Minimum',
        '작게': 'Small',
        '기본': 'Default',
        '크게': 'Large',
        '최대': 'Maximum',
        '암전': 'Blackout',
        '루멘': 'Lumen',
        '사이드': 'Side',
        '삭제': 'Delete',
        '카드는 드래그해서 원하는 영역으로 옮깁니다. 자신의 카드는 자신의 영역 대부분으로 이동할 수 있고, 상대 영역으로는 루멘 존과 배틀 존까지 이동할 수 있습니다.': 'Drag cards to move them to the desired zone. Your cards can move to most of your own zones, and to your opponent’s Lumen Zone or Battle Zone.',
        '손패, 사이드 덱, 루멘 존, 배틀 존은 공개와 비공개를 선택할 수 있는 영역입니다. 카드를 우클릭하거나 카드 오른쪽 위의 눈 모양 버튼을 누르면 공개 상태를 바꿀 수 있습니다. 공개 여부를 바꿀 권한은 카드의 소유자에게 있습니다.': 'Hand, Side Deck, Lumen Zone, and Battle Zone support visible and hidden states. Right-click a card or press the eye button at the top right of the card to toggle visibility. Only the card owner can change its visibility.',
        '배틀 존 전체를 리스트나 손패로 보내는 일괄 버튼도 사용할 수 있습니다. 배틀 페이즈가 끝날 때는 배틀 페이즈 돌입 시 이미 배틀 존에 있던 카드는 손패로 돌아가고, 이후 배틀 존에 놓인 카드는 리스트로 이동합니다.': 'You can also use bulk buttons to send the entire Battle Zone to the List or Hand. When the Battle Phase ends, cards that were already in the Battle Zone when the phase began return to Hand, while cards placed there afterward move to the List.',
        '행동 요청은 현재 어느 플레이어가 선택이나 조작을 해야 하는지 표시하는 기능입니다. 행동이 요구된 플레이어 영역은 강조 표시됩니다.': 'Action requests show which player currently needs to make a choice or operation. The requested player’s area is highlighted.',
        '자신의 행동이 끝났다면 내 행동 완료를 누릅니다. 한쪽이 완료한 상태에서 상대가 아직 완료하지 않았다면, 상대에게 행동 요청이 자동으로 표시됩니다. 양쪽이 모두 완료하면 다음 페이즈로 넘어갑니다.': 'When your action is finished, press My Action Done. If one player is done and the other is not, an action request is shown to the other player automatically. When both players are done, the simulator advances to the next phase.',
        '단축키로는 Space가 내 행동 완료, Shift + Space가 상대에게 행동 요청입니다. Z, X, C는 각각 효과 발동, 콤보 타임, 캐치 타임 신호를 보내며 양쪽 화면 중앙에 크게 표시됩니다.': 'For shortcuts, Space marks your action done, and Shift + Space requests action from your opponent. Z, X, and C send Effect Activation, Combo Time, and Catch Time signals, shown prominently in the center of both screens.',
        '로그 버튼을 누르면 오른쪽에서 로그 창이 열립니다. 카드 이동, 페이즈 변경, 공개/비공개 전환, HP/FP 변화, 수동 기록이 순서대로 표시됩니다.': 'Press the Log button to open the log panel on the right. Card movement, phase changes, visibility toggles, HP/FP changes, and manual notes are shown in order.',
        '내 행동과 관련된 로그는 내 쪽 정렬, 상대 행동과 관련된 로그는 상대 쪽 정렬, 페이즈 전환처럼 공통인 로그는 중앙 정렬로 표시됩니다. 카드명이 포함된 로그는 클릭해서 카드 정보를 확인할 수 있습니다.': 'Logs related to your actions are aligned to your side, logs related to your opponent are aligned to their side, and shared logs such as phase changes are centered. Logs containing card names can be clicked to view card information.',
        '로그 입력칸에 내용을 입력하고 Enter를 누르면 직접 기록을 남길 수 있습니다. 빠른 로그 버튼으로 히트, 카운터, 방어, 회피 같은 결과도 바로 남길 수 있습니다.': 'Type into the log input and press Enter to add a manual note. Quick log buttons can record results such as Hit, Counter, Guard, and Evade.',
        '패시브 영역에는 캐릭터의 패시브 카드와 관련 조작이 표시됩니다. 카운터를 쌓거나 상태를 켜고 끄는 패시브는 버튼으로 관리할 수 있습니다.': 'The passive area shows the character’s passive cards and related controls. Passives that use counters or on/off states can be managed with buttons.',
        '캐릭터별로 별도 조작이 필요한 경우 전용 UI가 표시됩니다. 예를 들어 요한은 예지와 디제스터 원 관련 조작을, 니아와 CMYK는 캐릭터 패시브에 맞는 전용 버튼을 사용할 수 있습니다.': 'If a character needs special controls, a dedicated UI is shown. For example, Yohan has controls for Foresight and Disaster One, while Nia and CMYK use buttons tailored to their passives.',
        '패시브 버튼은 상태 표시를 돕기 위한 기능이며, 게임 규칙의 적법성이나 카드 효과의 성공 여부를 자동 판정하지 않습니다. 필요한 판단은 플레이어가 직접 확인하고 로그로 남겨주세요.': 'Passive buttons are only state-tracking aids. They do not automatically judge rules legality or whether a card effect succeeds. Players should confirm necessary rulings themselves and record them in the log.',
        '시뮬레이터는 카드 효과를 자동으로 계산하지 않습니다. 공개된 카드를 클릭하면 카드 이미지와 주요 텍스트를 확인할 수 있고, 그 내용을 바탕으로 플레이어가 직접 처리합니다.': 'The simulator does not automatically calculate card effects. Click a revealed card to view its image and key text, then resolve it manually based on that information.',
        '일부 자주 쓰는 복잡한 처리는 카드 정보 창의 기능 버튼으로 보조할 수 있습니다. 예를 들어 블랙아웃처럼 실제 절차가 번거로운 효과는 버튼을 통해 대체 처리를 빠르게 수행할 수 있습니다.': 'Some frequently used complex procedures are assisted by function buttons in the card information panel. For effects with cumbersome physical procedures, such as Blackout, buttons can perform the substitute procedure quickly.',
        '효과 처리를 시작할 때는 Z를 눌러 효과 발동 신호를 보내면 상대 화면에도 같은 신호가 표시됩니다. 처리 결과는 로그 입력 또는 빠른 로그 버튼으로 남겨두는 것이 좋습니다.': 'When starting effect resolution, press Z to send an Effect Activation signal, which appears on your opponent’s screen as well. It is recommended to record the result with a log entry or a quick log button.',
        '두 플레이어의 덱 ID를 입력해 카드 존, 페이즈, 로그를 실시간으로 공유하는 세션을 만듭니다.': 'Enter both deck IDs to create a shared live session for zones, phases, and logs.',
        '시뮬레이터 시작': 'Start Simulator',
        '덱 ID를 확인해주세요.': 'Please check the deck IDs.',
        '플레이어1 덱을 볼 권한이 없습니다.': 'You do not have permission to view the Player 1 deck.',
        '플레이어2 덱을 볼 권한이 없습니다.': 'You do not have permission to view the Player 2 deck.',
        'P1 링크': 'P1 Link',
        'P2 링크': 'P2 Link',
        '카드명': 'Card Name',
        '루멘에 생성': 'Create in Lumen',
        '루멘 페이즈에 처리할 효과를 처리하세요': 'Resolve effects for the Lumen Phase.',
        '기술을 배틀 존에 레디하세요': 'Ready a technique in the Battle Zone.',
        '상대와의 배틀 결과를 처리하세요': 'Resolve the battle result with your opponent.',
        '리스트에서 기술을 획득하세요': 'Get a technique from the List.',
        '리커버리 페이즈에 처리할 효과를 처리하세요': 'Resolve effects for the Recovery Phase.',
        '다음 턴': 'Next Turn',
        '카드 정보': 'Card Info',
        '로그': 'Log',
        '접기': 'Collapse',
        '단축키': 'Shortcuts',
        '로그 켜기': 'Toggle Log',
        '상대에게 행동 요청': 'Request Opponent Action',
        '카드 우클릭': 'Right-click Card',
        '카드 공개/비공개 전환': 'Toggle Card Visibility',
        '손패 셔플': 'Shuffle Hand',
        '자신 HP -500 / -100 / +100 / +500': 'Own HP -500 / -100 / +100 / +500',
        '자신 FP -1 / +1': 'Own FP -1 / +1',
        '상대 HP -500 / -100 / +100 / +500': 'Opponent HP -500 / -100 / +100 / +500',
        '상대 FP -1 / +1': 'Opponent FP -1 / +1',
        '자신': 'Self',
        '상대': 'Opponent',
        '로그 입력': 'Log Entry',
        '히트': 'Hit',
        '카운터': 'Counter',
        '대응 없음': 'No Response',
        '효과 발동': 'Effect Activation',
        '콤보 타임': 'Combo Time',
        '캐치 타임': 'Catch Time',
        '신호': 'Signal',
        '신호가 올바르지 않습니다.': 'Invalid signal.',
        '효과 발동 / 콤보 타임 / 캐치 타임': 'Effect Activation / Combo Time / Catch Time',
        '관전': 'Viewer',
        'P1 조작 링크로 접속 중입니다.': 'Connected with the P1 control link.',
        'P2 조작 링크로 접속 중입니다.': 'Connected with the P2 control link.',
        '관전 링크로 접속 중입니다. 조작은 비활성화됩니다.': 'Connected as a viewer. Controls are disabled.',
        '비공개 카드': 'Hidden Card',
        '요청을 처리하지 못했습니다.': 'Could not process the request.',
        '요청 응답 시간이 초과되었습니다.': 'Request timed out.',
        '네트워크 오류가 발생했습니다.': 'A network error occurred.',
        '완료': 'Done',
        '요청됨': 'Requested',
        '대기': 'Waiting',
        '요청 해제': 'Cancel Request',
        '행동 요청': 'Request Action',
        '완료 취소': 'Cancel Done',
        '내 행동 완료': 'My Action Done',
        '활성': 'Active',
        '발동': 'Activate',
        '예지': 'Foresight',
        '예지 카운터': 'Foresight Counter',
        '디제스터 원': 'Disaster One',
        '선언': 'Declare',
        '배틀 카드 공개': 'Battle Cards Revealed',
        '홀': 'Odd',
        '짝': 'Even',
        '공': 'Atk',
        '수': 'Def',
        '홀수': 'Odd',
        '짝수': 'Even',
        '패시브 UI 오류': 'Passive UI Error',
        '리스트': 'List',
        '비공개로 전환': 'Make Hidden',
        '공개로 전환': 'Reveal',
        '카드': 'Card',
        '장': ' cards',
        '행동': 'Action',
        '요청': 'Request',
        '공개': 'Revealed',
        '비공개': 'Hidden',
        '표시할 로그가 없습니다.': 'No logs to show.',
        '상대 플레이어의 루멘 존 또는 배틀 존으로만 이동할 수 있습니다.': 'You can only move cards to the opponent\'s Lumen Zone or Battle Zone.',
        '시뮬레이터 연결이 끊겼습니다.': 'Simulator connection was lost.',
        '조작 권한이 없습니다.': 'You do not have control permission.',
        '계산기 세션을 찾을 수 없습니다.': 'Calculator session not found.',
        '시뮬레이터 세션을 찾을 수 없습니다.': 'Simulator session not found.',
        '알 수 없는 요청입니다.': 'Unknown request.',
        '이동할 존이 올바르지 않습니다.': 'The destination zone is invalid.',
        '이동할 카드를 찾을 수 없습니다.': 'Could not find the card to move.',
        '캐릭터 카드는 이동할 수 없습니다.': 'Character cards cannot be moved.',
        '이동할 플레이어가 올바르지 않습니다.': 'The destination player is invalid.',
        '일괄 이동 대상이 올바르지 않습니다.': 'The bulk move target is invalid.',
        '지원하지 않는 일괄 이동입니다.': 'Unsupported bulk move.',
        '페이즈가 올바르지 않습니다.': 'The phase is invalid.',
        '요청 대상이 올바르지 않습니다.': 'The request target is invalid.',
        '완료 대상이 올바르지 않습니다.': 'The done target is invalid.',
        '체력 변경값이 올바르지 않습니다.': 'Invalid HP change.',
        'FP 변경값이 올바르지 않습니다.': 'Invalid FP change.',
        'FP 초기화 대상이 올바르지 않습니다.': 'Invalid FP reset target.',
        '패시브 대상이 올바르지 않습니다.': 'Invalid passive target.',
        '공개 상태를 변경할 카드를 찾을 수 없습니다.': 'Could not find the card to change visibility.',
        '공개 존의 카드는 비공개로 전환할 수 없습니다.': 'Cards in public zones cannot be hidden.',
        '기록할 내용을 입력해주세요.': 'Enter text to log.',
        '가져올 카드명을 입력해주세요.': 'Enter a card name to import.',
        '해당 이름의 카드를 찾을 수 없습니다.': 'No card matched that name.',
        '이미 생성된 카드입니다.': 'This card has already been created.',
        '가져올 카드를 찾을 수 없습니다.': 'Could not find the card to import.',
        '되돌릴 행동이 없습니다.': 'There is no action to undo.',
        '링크': 'Link',
        'Lumen': 'Lumen',
        'Ready': 'Ready',
        'Battle': 'Battle',
        'Get': 'Get',
        'Recovery': 'Recovery',
        'Character Zone': 'Character Zone',
        'Passive Zone': 'Passive Zone',
        'Battle Zone': 'Battle Zone',
        'Side Deck': 'Side Deck',
        'Break Zone': 'Break Zone',
        'Lumen Zone': 'Lumen Zone',
        'Ultimate Zone': 'Ultimate Zone',
        'Phase': 'Phase',
    },
    LANGUAGE_JAPANESE: {
        '대전 계산기': '対戦計算機',
        '두 플레이어의 캐릭터를 선택해 체력, 손패 제한, 패시브 기록을 관리합니다.': '両プレイヤーのキャラクターを選び、HP、手札上限、パッシブ記録を管理します。',
        '플레이어1 이름': 'プレイヤー1 名',
        '플레이어2 이름': 'プレイヤー2 名',
        '플레이어1 캐릭터': 'プレイヤー1 キャラクター',
        '플레이어2 캐릭터': 'プレイヤー2 キャラクター',
        '플레이어1 덱 ID': 'プレイヤー1 デッキID',
        '플레이어2 덱 ID': 'プレイヤー2 デッキID',
        '계산기 시작': '計算機を開始',
        '플레이어1': 'プレイヤー1',
        '플레이어2': 'プレイヤー2',
        '로그 닫기': 'ログを閉じる',
        '공유 닫기': '共有を閉じる',
        '링크 공유': 'リンク共有',
        '관전 링크 복사': '観戦リンクをコピー',
        '조작 링크 복사': '操作リンクをコピー',
        '관전 링크': '観戦リンク',
        '조작 링크': '操作リンク',
        '닫기': '閉じる',
        '초기화': '初期化',
        '손패 -': '手札 -',
        '손패': '手札',
        '대회 복귀': '大会へ戻る',
        '게임 시간': 'ゲーム時間',
        '서든 데스': 'サドンデス',
        '서든 데스 해제': 'サドンデス解除',
        '10초 타이머': '10秒タイマー',
        '10초': '10秒',
        '결과 보고': '結果報告',
        '보고 완료': '報告済み',
        '되돌리기': '取り消し',
        '로그 확인': 'ログ確認',
        '전체화면': '全画面',
        '기록': '記録',
        '전체': '全体',
        '선택': '選択',
        '결과 확정': '結果確定',
        '승으로 확정': '勝利で確定',
        '추가 시간': '追加時間',
        '추가 턴 종료': '追加ターン終了',
        '남은 추가 턴': '残り追加ターン',
        '턴': 'ターン',
        '세트': 'セット',
        '세트 시작': 'セット開始',
        '세트 결과 확인': 'セット結果確認',
        '체력 변경 되돌림': 'HP変更取り消し',
        '10초 타이머 시작': '10秒タイマー開始',
        '10초 타이머 정지': '10秒タイマー停止',
        '서든 데스 진입': 'サドンデス開始',
        '서든 데스 추가 턴 종료': 'サドンデス追加ターン終了',
        '남은 턴': '残りターン',
        '패시브 패널 스크립트 오류가 발생했습니다.': 'パッシブパネルのスクリプトエラーが発生しました。',
        '캐릭터를 선택하면 패시브 패널이 표시됩니다.': 'キャラクターを選ぶとパッシブパネルが表示されます。',
        '표시할 기록이 없습니다.': '表示する記録がありません。',
        '계산기 연결이 끊겼습니다.': '計算機の接続が切れました。',
        '계산기 세션을 초기화할까요? 현재 HP, FP, 패시브, 타이머, 로그가 초기 상태로 돌아갑니다.': '計算機セッションを初期化しますか？現在のHP、FP、パッシブ、タイマー、ログが初期状態に戻ります。',
        '일반 계산기 세션만 초기화할 수 있습니다.': '通常計算機セッションのみ初期化できます。',
        '서든 데스에 진입할까요? 각 플레이어의 HP는 1000, FP는 0이 되고 추가 턴 3턴이 시작됩니다.': 'サドンデスに入りますか？各プレイヤーのHPは1000、FPは0になり、追加3ターンが始まります。',
        '서든 데스를 해제할까요?': 'サドンデスを解除しますか？',
        '루멘콘덴서 시뮬레이터': 'ルーメンコンデンサー シミュレーター',
        '모바일': 'モバイル',
        '모바일 시뮬레이터': 'モバイルシミュレーター',
        '데스크톱': 'デスクトップ',
        '접속': '接続',
        '새로고침': '更新',
        '카드가 없습니다.': 'カードがありません。',
        '시뮬레이터 가이드': 'シミュレーターガイド',
        '가이드': 'ガイド',
        '루멘콘덴서 웹 시뮬레이터는 카드 효과를 자동 판정하지 않고, 두 플레이어가 같은 보드와 로그를 보며 진행을 맞추는 도구입니다.': 'ルーメンコンデンサーWebシミュレーターはカード効果を自動判定せず、両プレイヤーが同じ盤面とログを見ながら進行を合わせるためのツールです。',
        '목차': '目次',
        '카드를 움직이는 법': 'カードの動かし方',
        '행동 요청과 행동 완료': '行動要求と行動完了',
        '패시브 효과': 'パッシブ効果',
        '카드 효과': 'カード効果',
        '카드 크기': 'カードサイズ',
        '카드 축소': 'カードを小さくする',
        '카드 확대': 'カードを大きくする',
        '최소': '最小',
        '작게': '小',
        '기본': '標準',
        '크게': '大',
        '최대': '最大',
        '암전': '暗転',
        '루멘': 'ルーメン',
        '사이드': 'サイド',
        '삭제': '削除',
        '카드는 드래그해서 원하는 영역으로 옮깁니다. 자신의 카드는 자신의 영역 대부분으로 이동할 수 있고, 상대 영역으로는 루멘 존과 배틀 존까지 이동할 수 있습니다.': 'カードはドラッグして目的の領域へ移動します。自分のカードは自分側のほとんどの領域へ移動でき、相手側へはルーメンゾーンとバトルゾーンまで移動できます。',
        '손패, 사이드 덱, 루멘 존, 배틀 존은 공개와 비공개를 선택할 수 있는 영역입니다. 카드를 우클릭하거나 카드 오른쪽 위의 눈 모양 버튼을 누르면 공개 상태를 바꿀 수 있습니다. 공개 여부를 바꿀 권한은 카드의 소유자에게 있습니다.': '手札、サイドデッキ、ルーメンゾーン、バトルゾーンは公開・非公開を選べる領域です。カードを右クリックするか、カード右上の目のボタンを押すと公開状態を切り替えられます。公開状態を変更できるのはカードの所有者です。',
        '배틀 존 전체를 리스트나 손패로 보내는 일괄 버튼도 사용할 수 있습니다. 배틀 페이즈가 끝날 때는 배틀 페이즈 돌입 시 이미 배틀 존에 있던 카드는 손패로 돌아가고, 이후 배틀 존에 놓인 카드는 리스트로 이동합니다.': 'バトルゾーン全体をリストや手札へ送る一括ボタンも使用できます。バトルフェイズ終了時、バトルフェイズ突入時点ですでにバトルゾーンにあったカードは手札へ戻り、その後バトルゾーンに置かれたカードはリストへ移動します。',
        '행동 요청은 현재 어느 플레이어가 선택이나 조작을 해야 하는지 표시하는 기능입니다. 행동이 요구된 플레이어 영역은 강조 표시됩니다.': '行動要求は、現在どちらのプレイヤーが選択や操作を行う必要があるかを示す機能です。行動を求められているプレイヤーの領域が強調表示されます。',
        '자신의 행동이 끝났다면 내 행동 완료를 누릅니다. 한쪽이 완료한 상태에서 상대가 아직 완료하지 않았다면, 상대에게 행동 요청이 자동으로 표시됩니다. 양쪽이 모두 완료하면 다음 페이즈로 넘어갑니다.': '自分の行動が終わったら「自分の行動完了」を押します。一方が完了し、相手がまだ完了していない場合、相手に行動要求が自動表示されます。両方が完了すると次のフェイズへ進みます。',
        '단축키로는 Space가 내 행동 완료, Shift + Space가 상대에게 행동 요청입니다. Z, X, C는 각각 효과 발동, 콤보 타임, 캐치 타임 신호를 보내며 양쪽 화면 중앙에 크게 표시됩니다.': 'ショートカットでは、Spaceが自分の行動完了、Shift + Spaceが相手への行動要求です。Z、X、Cはそれぞれ効果発動、コンボタイム、キャッチタイムのシグナルを送り、両方の画面中央に大きく表示されます。',
        '로그 버튼을 누르면 오른쪽에서 로그 창이 열립니다. 카드 이동, 페이즈 변경, 공개/비공개 전환, HP/FP 변화, 수동 기록이 순서대로 표시됩니다.': 'ログボタンを押すと右側からログパネルが開きます。カード移動、フェイズ変更、公開/非公開切替、HP/FP変化、手動記録が順番に表示されます。',
        '내 행동과 관련된 로그는 내 쪽 정렬, 상대 행동과 관련된 로그는 상대 쪽 정렬, 페이즈 전환처럼 공통인 로그는 중앙 정렬로 표시됩니다. 카드명이 포함된 로그는 클릭해서 카드 정보를 확인할 수 있습니다.': '自分の行動に関するログは自分側に、相手の行動に関するログは相手側に、フェイズ移行のような共通ログは中央に表示されます。カード名を含むログはクリックしてカード情報を確認できます。',
        '로그 입력칸에 내용을 입력하고 Enter를 누르면 직접 기록을 남길 수 있습니다. 빠른 로그 버튼으로 히트, 카운터, 방어, 회피 같은 결과도 바로 남길 수 있습니다.': 'ログ入力欄に内容を入力してEnterを押すと手動記録を残せます。クイックログボタンでヒット、カウンター、防御、回避などの結果もすぐに残せます。',
        '패시브 영역에는 캐릭터의 패시브 카드와 관련 조작이 표시됩니다. 카운터를 쌓거나 상태를 켜고 끄는 패시브는 버튼으로 관리할 수 있습니다.': 'パッシブ領域にはキャラクターのパッシブカードと関連操作が表示されます。カウンターを貯めたり状態をオン/オフするパッシブはボタンで管理できます。',
        '캐릭터별로 별도 조작이 필요한 경우 전용 UI가 표시됩니다. 예를 들어 요한은 예지와 디제스터 원 관련 조작을, 니아와 CMYK는 캐릭터 패시브에 맞는 전용 버튼을 사용할 수 있습니다.': 'キャラクターごとに個別操作が必要な場合は専用UIが表示されます。たとえばヨハンは予知とディザスター・ワン関連の操作を、ニアとCMYKはキャラクターパッシブに合わせた専用ボタンを使用できます。',
        '패시브 버튼은 상태 표시를 돕기 위한 기능이며, 게임 규칙의 적법성이나 카드 효과의 성공 여부를 자동 판정하지 않습니다. 필요한 판단은 플레이어가 직접 확인하고 로그로 남겨주세요.': 'パッシブボタンは状態表示を補助する機能であり、ゲームルール上の適法性やカード効果の成否を自動判定するものではありません。必要な判断はプレイヤー同士で確認し、ログに残してください。',
        '시뮬레이터는 카드 효과를 자동으로 계산하지 않습니다. 공개된 카드를 클릭하면 카드 이미지와 주요 텍스트를 확인할 수 있고, 그 내용을 바탕으로 플레이어가 직접 처리합니다.': 'シミュレーターはカード効果を自動計算しません。公開されたカードをクリックするとカード画像と主要テキストを確認でき、その内容をもとにプレイヤーが手動で処理します。',
        '일부 자주 쓰는 복잡한 처리는 카드 정보 창의 기능 버튼으로 보조할 수 있습니다. 예를 들어 블랙아웃처럼 실제 절차가 번거로운 효과는 버튼을 통해 대체 처리를 빠르게 수행할 수 있습니다.': '一部のよく使う複雑な処理は、カード情報ウィンドウの機能ボタンで補助できます。たとえばブラックアウトのように実際の手順が煩雑な効果は、ボタンで代替処理を素早く実行できます。',
        '효과 처리를 시작할 때는 Z를 눌러 효과 발동 신호를 보내면 상대 화면에도 같은 신호가 표시됩니다. 처리 결과는 로그 입력 또는 빠른 로그 버튼으로 남겨두는 것이 좋습니다.': '効果処理を始めるときはZを押して効果発動シグナルを送ると、相手画面にも同じシグナルが表示されます。処理結果はログ入力またはクイックログボタンで残しておくとよいです。',
        '두 플레이어의 덱 ID를 입력해 카드 존, 페이즈, 로그를 실시간으로 공유하는 세션을 만듭니다.': '両プレイヤーのデッキIDを入力し、カードゾーン、フェイズ、ログをリアルタイムで共有するセッションを作成します。',
        '시뮬레이터 시작': 'シミュレーター開始',
        '덱 ID를 확인해주세요.': 'デッキIDを確認してください。',
        '플레이어1 덱을 볼 권한이 없습니다.': 'プレイヤー1のデッキを見る権限がありません。',
        '플레이어2 덱을 볼 권한이 없습니다.': 'プレイヤー2のデッキを見る権限がありません。',
        'P1 링크': 'P1リンク',
        'P2 링크': 'P2リンク',
        '카드명': 'カード名',
        '루멘에 생성': 'ルーメンに生成',
        '루멘 페이즈에 처리할 효과를 처리하세요': 'ルーメンフェイズで処理する効果を処理してください。',
        '기술을 배틀 존에 레디하세요': '技をバトルゾーンにレディしてください。',
        '상대와의 배틀 결과를 처리하세요': '相手とのバトル結果を処理してください。',
        '리스트에서 기술을 획득하세요': 'リストから技を獲得してください。',
        '리커버리 페이즈에 처리할 효과를 처리하세요': 'リカバリーフェイズで処理する効果を処理してください。',
        '다음 턴': '次のターン',
        '카드 정보': 'カード情報',
        '로그': 'ログ',
        '접기': '折りたたむ',
        '단축키': 'ショートカット',
        '로그 켜기': 'ログを開閉',
        '상대에게 행동 요청': '相手に行動要求',
        '카드 우클릭': 'カード右クリック',
        '카드 공개/비공개 전환': 'カードの公開/非公開切替',
        '손패 셔플': '手札シャッフル',
        '자신 HP -500 / -100 / +100 / +500': '自分 HP -500 / -100 / +100 / +500',
        '자신 FP -1 / +1': '自分 FP -1 / +1',
        '상대 HP -500 / -100 / +100 / +500': '相手 HP -500 / -100 / +100 / +500',
        '상대 FP -1 / +1': '相手 FP -1 / +1',
        '자신': '自分',
        '상대': '相手',
        '로그 입력': 'ログ入力',
        '히트': 'ヒット',
        '카운터': 'カウンター',
        '대응 없음': '対応なし',
        '효과 발동': '効果発動',
        '콤보 타임': 'コンボタイム',
        '캐치 타임': 'キャッチタイム',
        '신호': 'シグナル',
        '신호가 올바르지 않습니다.': 'シグナルが正しくありません。',
        '효과 발동 / 콤보 타임 / 캐치 타임': '効果発動 / コンボタイム / キャッチタイム',
        '관전': '観戦',
        'P1 조작 링크로 접속 중입니다.': 'P1操作リンクで接続中です。',
        'P2 조작 링크로 접속 중입니다.': 'P2操作リンクで接続中です。',
        '관전 링크로 접속 중입니다. 조작은 비활성화됩니다.': '観戦リンクで接続中です。操作は無効です。',
        '비공개 카드': '非公開カード',
        '요청을 처리하지 못했습니다.': 'リクエストを処理できませんでした。',
        '요청 응답 시간이 초과되었습니다.': 'リクエストがタイムアウトしました。',
        '네트워크 오류가 발생했습니다.': 'ネットワークエラーが発生しました。',
        '완료': '完了',
        '요청됨': '要求済み',
        '대기': '待機',
        '요청 해제': '要求解除',
        '행동 요청': '行動要求',
        '완료 취소': '完了取消',
        '내 행동 완료': '自分の行動完了',
        '활성': '有効',
        '발동': '発動',
        '예지': '予知',
        '예지 카운터': '予知カウンター',
        '디제스터 원': 'ディザスター・ワン',
        '선언': '宣言',
        '배틀 카드 공개': 'バトルカード公開',
        '홀': '奇',
        '짝': '偶',
        '공': '攻',
        '수': '防',
        '홀수': '奇数',
        '짝수': '偶数',
        '패시브 UI 오류': 'パッシブUIエラー',
        '리스트': 'リスト',
        '비공개로 전환': '非公開にする',
        '공개로 전환': '公開する',
        '카드': 'カード',
        '장': '枚',
        '행동': '行動',
        '요청': '要求',
        '공개': '公開',
        '비공개': '非公開',
        '표시할 로그가 없습니다.': '表示するログがありません。',
        '상대 플레이어의 루멘 존 또는 배틀 존으로만 이동할 수 있습니다.': '相手プレイヤーのルーメンゾーンまたはバトルゾーンにのみ移動できます。',
        '시뮬레이터 연결이 끊겼습니다.': 'シミュレーターの接続が切れました。',
        '조작 권한이 없습니다.': '操作権限がありません。',
        '계산기 세션을 찾을 수 없습니다.': '計算機セッションが見つかりません。',
        '시뮬레이터 세션을 찾을 수 없습니다.': 'シミュレーターセッションが見つかりません。',
        '알 수 없는 요청입니다.': '不明なリクエストです。',
        '이동할 존이 올바르지 않습니다.': '移動先ゾーンが正しくありません。',
        '이동할 카드를 찾을 수 없습니다.': '移動するカードが見つかりません。',
        '캐릭터 카드는 이동할 수 없습니다.': 'キャラクターカードは移動できません。',
        '이동할 플레이어가 올바르지 않습니다.': '移動先プレイヤーが正しくありません。',
        '일괄 이동 대상이 올바르지 않습니다.': '一括移動対象が正しくありません。',
        '지원하지 않는 일괄 이동입니다.': '対応していない一括移動です。',
        '페이즈가 올바르지 않습니다.': 'フェイズが正しくありません。',
        '요청 대상이 올바르지 않습니다.': '要求対象が正しくありません。',
        '완료 대상이 올바르지 않습니다.': '完了対象が正しくありません。',
        '체력 변경값이 올바르지 않습니다.': 'HP変更値が正しくありません。',
        'FP 변경값이 올바르지 않습니다.': 'FP変更値が正しくありません。',
        'FP 초기화 대상이 올바르지 않습니다.': 'FP初期化対象が正しくありません。',
        '패시브 대상이 올바르지 않습니다.': 'パッシブ対象が正しくありません。',
        '공개 상태를 변경할 카드를 찾을 수 없습니다.': '公開状態を変更するカードが見つかりません。',
        '공개 존의 카드는 비공개로 전환할 수 없습니다.': '公開ゾーンのカードは非公開にできません。',
        '기록할 내용을 입력해주세요.': '記録する内容を入力してください。',
        '가져올 카드명을 입력해주세요.': '取り込むカード名を入力してください。',
        '해당 이름의 카드를 찾을 수 없습니다.': 'その名前のカードが見つかりません。',
        '이미 생성된 카드입니다.': 'すでに生成されたカードです。',
        '가져올 카드를 찾을 수 없습니다.': '取り込むカードが見つかりません。',
        '되돌릴 행동이 없습니다.': '取り消す行動がありません。',
        '링크': 'リンク',
        'Lumen': 'ルーメン',
        'Ready': 'レディ',
        'Battle': 'バトル',
        'Get': 'ゲット',
        'Recovery': 'リカバリー',
        'Character Zone': 'キャラクターゾーン',
        'Passive Zone': 'パッシブゾーン',
        'Battle Zone': 'バトルゾーン',
        'Hand': '手札',
        'List': 'リスト',
        'Side Deck': 'サイドデッキ',
        'Break Zone': 'ブレイクゾーン',
        'Lumen Zone': 'ルーメンゾーン',
        'Ultimate Zone': 'アルティメットゾーン',
        'Phase': 'フェイズ',
    },
}

for _language, _translations in TOOL_UI_TRANSLATIONS.items():
    UI_TRANSLATIONS.setdefault(_language, {}).update(_translations)

UI_TRANSLATIONS[LANGUAGE_ENGLISH].update({
    '공통': 'Shared',
    'FP 초기화': 'FP Reset',
    '이번 턴 변화': 'This turn change',
    '계산기 상태가 오래되었습니다.': 'The counter state is outdated.',
    '이미 다른 계산기 조작이 먼저 반영되었습니다.': 'Another counter change was applied first.',
    '승': 'wins',
    '시작': 'Start',
    '+1분': '+1 min',
    '+3분': '+3 min',
    '+5분': '+5 min',
})
UI_TRANSLATIONS[LANGUAGE_JAPANESE].update({
    '공통': '共通',
    'FP 초기화': 'FP初期化',
    '이번 턴 변화': 'このターンの変化',
    '계산기 상태가 오래되었습니다.': '計算機の状態が古くなっています。',
    '이미 다른 계산기 조작이 먼저 반영되었습니다.': '他の計算機操作が先に反映されました。',
    '승': '勝利',
    '시작': '開始',
    '+1분': '+1分',
    '+3분': '+3分',
    '+5분': '+5分',
})

UI_TRANSLATIONS[LANGUAGE_ENGLISH].update({
    '개': '',
    '종': ' types',
    '점': ' pts',
    '명': ' people',
    '덱 만들기': 'Create Deck',
    '덱 수정': 'Edit Deck',
    '덱 생성': 'Create Deck',
    '수정 저장': 'Save Changes',
    '덱 이름': 'Deck Name',
    '공개 범위': 'Visibility',
    '덱 설명': 'Deck Description',
    '덱 설명 열기': 'Open Deck Description',
    '덱 설명 닫기': 'Close Deck Description',
    '카드를 검색해 추가하고, 카드 이미지의 하단 버튼으로 표시 영역을 조정합니다. 버전은 덱의 최신 카드 기준으로 자동 지정됩니다.': 'Search and add cards, then use the buttons under each card image to move it between areas. The version is set automatically from the newest card in the deck.',
    '검색어': 'Search Term',
    '카드명, 키워드': 'Card name, keyword',
    '전체': 'Total',
    '리스트': 'List',
    '손패': 'Hand',
    '사이드': 'Side',
    '얼티밋': 'Ultimate',
    '얼티밋 카드': 'Ultimate Card',
    '덱 매수는 최대 {count}장입니다.': 'A deck can contain up to {count} cards.',
    '얼티밋 카드는 1장까지만 넣을 수 있습니다.': 'Only one ultimate card can be added.',
    '손패 매수는 최대 5장입니다.': 'The hand area can contain up to 5 cards.',
    '이 카드는 더 넣을 수 없습니다.': 'This card cannot be added any more.',
    '얼티밋 카드는 얼티밋 영역에 별도로 표시됩니다.': 'Ultimate cards are shown separately in the ultimate area.',
    '키워드, 작성자 검색': 'Search keyword or author',
    '최신순': 'Newest',
    '버전순': 'Version',
    '좋아요순': 'Likes',
    '덱 검색': 'Deck Search',
    '덱 이름, 캐릭터, 태그를 바탕으로 덱을 검색합니다.': 'Search decks by deck name, character, or tags.',
    '통계': 'Stats',
    '추천': 'Likes',
    '상세 보기': 'View Details',
    '텍스트로 보기': 'Text View',
    '이미지로 보기': 'Image View',
    '텍스트 덱 복사': 'Copy Deck Text',
    '덱 복사': 'Copy Deck',
    '덱 캡쳐': 'Capture Deck',
    '덱 삭제': 'Delete Deck',
    '대회 제출 덱 잠금': 'Tournament Submission Locked',
    '복사할 덱 리스트가 없습니다.': 'There is no deck list to copy.',
    '클립보드에 복사되었습니다!': 'Copied to clipboard!',
    '이미지 생성 중...': 'Generating image...',
    '컬렉션 카드 추가': 'Add Collection Card',
    '별도 판본, 스킨, 프로모 수록 정보를 등록합니다.': 'Register alternate printings, skins, and promo entries.',
    '연결 카드': 'Linked Card',
    '이미지(webp)': 'Image (webp)',
    '팩': 'Pack',
    '저장': 'Save',
    '저장됨': 'Saved',
    '저장에 실패했습니다.': 'Failed to save.',
    '미보유만 보기': 'Missing Only',
    '수록 카드, 레어도, 보유 수량을 한 화면에서 확인하고 정리합니다.': 'Review and manage printings, rarity, and owned counts in one view.',
    '수량을 변경한 뒤 저장 버튼을 눌러주세요. 카드명 또는 코드를 누르면 정렬 기준이 바뀝니다.': 'After changing counts, press Save. Click card name or code to change sorting.',
    '이미지': 'Image',
    '코드': 'Code',
    '레어도 / 보유': 'Rarity / Owned',
    '정렬방향': 'Sort Direction',
    '미수집 카드만': 'Missing Cards Only',
    '이름순': 'Name',
    '코드순': 'Code',
    '오름차순': 'Ascending',
    '내림차순': 'Descending',
    '레어리티': 'Rarity',
    '검색 키워드 목록': 'Search keyword list',
    'N : 노멀': 'N : Normal',
    'SR : 슈퍼 레어': 'SR : Super Rare',
    'EXR : 익스텐드 레어': 'EXR : Extend Rare',
    'AN : 어나더 노멀': 'AN : Another Normal',
    'AEX : 어나더 익스텐드 레어': 'AEX : Another Extend Rare',
    'SAR : 시크릿 어나더 익스텐드 레어': 'SAR : Secret Another Extend Rare',
    'SP : 스페셜': 'SP : Special',
    '대회 운영': 'Tournament Operations',
    '대회 목록': 'Tournament List',
    '대회 검색': 'Tournament Search',
    '대회 상세 본문 영역': 'Tournament detail sections',
    '라운드': 'Rounds',
    '상세': 'Detail',
    '설정 편집': 'Edit Settings',
    '세츠메이': 'Setsumei',
    '우승': 'Winner',
    '운영자': 'Organizer',
    '작성자': 'Author',
    '루멘콘덴서 대회를 생성하거나, 대회 목록을 확인합니다.': 'Create LumenCondensor tournaments or browse tournament listings.',
    '대회 생성': 'Create Tournament',
    '대회 찾기': 'Find Tournaments',
    '전체 상태': 'All Statuses',
    '참가 코드로 참가': 'Join by Code',
    '참가 코드': 'Join Code',
    '일부 공개 대회는 운영자가 공유한 참가 코드나 QR 링크로 입장할 수 있습니다.': 'Unlisted tournaments can be entered through an organizer-shared join code or QR link.',
    '보기': 'View',
    '아직 등록된 대회가 없습니다.': 'No tournaments have been registered yet.',
    '대회 설명이 없습니다.': 'No tournament description.',
    '덱 리스트': 'Deck Lists',
    '덱 리스트 미요구': 'No Deck List Required',
    '스위스': 'Swiss',
    '토너먼트': 'Tournament',
    '스위스 + 토너먼트': 'Swiss + Tournament',
    '동률': 'Tiebreaker',
    '싱글 엘리미네이션': 'Single Elimination',
    '더블 엘리미네이션': 'Double Elimination',
    '참가 접수': 'Registration',
    '진행 중': 'Running',
    '종료': 'Finished',
    '공개': 'Public',
    '일부 공개': 'Unlisted',
    '비공개': 'Private',
    '대회 일시': 'Tournament Date',
    '대회명': 'Tournament Name',
    '장소': 'Venue',
    '운영 방식': 'Format',
    '토너먼트 방식': 'Elimination Mode',
    '대회 태그': 'Tournament Tags',
    '요구 덱 리스트 수': 'Required Deck Lists',
    '라운드 시간': 'Round Time',
    '라운드 세트 수': 'Sets per Round',
    '스위스 라운드 수': 'Swiss Round Count',
    '토너먼트 진출자 수': 'Top Cut Count',
    '동률 처리 기준': 'Tiebreaker',
    '승리 점수': 'Win Points',
    '무승부 점수': 'Draw Points',
    '패배 점수': 'Loss Points',
    '최대 참가자': 'Max Players',
    '설명': 'Description',
    '비워두면 자동 생성': 'Leave blank to auto-generate',
    '예: 공식/시즌1/입문': 'Example: official/season1/beginner',
    '0이면 제한 없음': '0 means no limit',
    '하이브리드 대회에서 사용': 'Used for hybrid tournaments',
    '공개 범위, 요구 덱 리스트 수, 기본 라운드 시간과 세트/점수 규칙을 설정합니다. 덱 리스트 수가 0이면 제출을 요구하지 않습니다.': 'Set visibility, required deck list count, default round time, sets, and points. A deck list count of 0 means no deck list is required.',
    '생성': 'Create',
    '대회 설정': 'Tournament Settings',
    '대회 진행 중에도 공개 범위, 참가 코드, 라운드 수, 토너먼트 컷, 세트/점수 규칙을 조정할 수 있습니다.': 'Visibility, join code, round count, top cut, sets, and points can be edited while the tournament is running.',
    '참가 정보': 'Entry Info',
    '대회 참가': 'Join Tournament',
    '현재 참가 접수가 닫혀 있습니다.': 'Registration is currently closed.',
    '참가 취소된 상태입니다. 다시 저장하면 참가 상태로 돌아갑니다.': 'Your entry is dropped. Saving again will re-enter the tournament.',
    '대회가 시작된 뒤에는 참가 정보와 제출 덱을 수정할 수 없습니다.': 'Entry information and submitted decks cannot be changed after the tournament starts.',
    '표시 이름': 'Display Name',
    '비워두면 계정 이름 사용': 'Leave blank to use account name',
    '대회 참가 코드를 입력': 'Enter tournament join code',
    '일부 공개 대회는 참가 코드가 있어야 참가 신청이 가능합니다.': 'Unlisted tournaments require a join code.',
    '이 대회는 덱 리스트': 'This tournament requires',
    '개 제출이 필요합니다.': ' deck list(s).',
    '공개 덱은 유저명이나 덱 이름으로 검색할 수 있고, 일부 공개 덱은 덱 ID를 입력하면 선택할 수 있습니다. 타인의 덱은 내 덱으로 복사된 뒤 제출됩니다.': 'Public decks can be searched by username or deck name. Unlisted decks can be selected by deck ID. Other users’ decks are copied into your decks before submission.',
    '유저명, 덱 이름, 일부 공개 덱 ID': 'Username, deck name, or unlisted deck ID',
    '선택된 덱이 없습니다.': 'No deck selected.',
    '제출 덱': 'Submitted Deck',
    '참가 정보 저장': 'Save Entry',
    '참가 신청': 'Join',
    '참가 취소': 'Drop',
    '로그인 후 참가할 수 있습니다.': 'Log in to join.',
    '참가 링크': 'Join Link',
    '로 바로 이 대회에 접근할 수 있습니다. QR 이미지는 QR 이미지 열기에서 확인할 수 있습니다.': ' gives direct access to this tournament. QR images are available from Open QR Image.',
    '참가 링크 열기': 'Open Join Link',
    'QR 이미지 열기': 'Open QR Image',
    '라운드 시작': 'Start Round',
    '우승자가 결정되어 더 이상 라운드를 생성할 수 없습니다.': 'A winner has been decided, so no more rounds can be created.',
    '매칭 방식': 'Pairing Method',
    '세트 수': 'Set Count',
    '일괄 매칭 및 시작': 'Pair and Start',
    '대회 종료': 'Finish Tournament',
    '이 대회를 삭제할까요? 삭제 후에는 되돌릴 수 없습니다.': 'Delete this tournament? This cannot be undone.',
    '종료되었거나 2라운드 이상 진행된 대회는 슈퍼유저만 삭제할 수 있습니다.': 'Only superusers can delete finished tournaments or tournaments that reached round 2 or later.',
    '대회 삭제': 'Delete Tournament',
    '미종료 테이블 서든 데스': 'Send Unfinished Tables to Sudden Death',
    '아직 종료되지 않은 모든 테이블을 서든 데스로 전환할까요? 각 계산기는 HP 1000, FP 0, 추가 턴 3턴 상태가 됩니다.': 'Move all unfinished tables to sudden death? Each calculator will restart at HP 1000, FP 0, with 3 extra turns.',
    '순위표': 'Standings',
    '참가': 'Entries',
    '토너먼트 진출': 'Top Cut',
    '순위': 'Rank',
    '참가자': 'Player',
    '덱 제출': 'Deck Submission',
    '점수': 'Points',
    '전적': 'Record',
    '비공개 덱': 'Private Deck',
    '미제출': 'Not Submitted',
    '제출': 'Submitted',
    '미요구': 'Not Required',
    '무': 'draws',
    '패': 'losses',
    '무승부': 'Draw',
    '토너먼트 진출 기준선': 'Top Cut Line',
    '아직 참가자가 없습니다.': 'No participants yet.',
    '라운드 선택': 'Round Selection',
    '계산기 대기': 'Calculator Waiting',
    '캐릭터 선택 필요': 'Character Required',
    '서든 데스': 'Sudden Death',
    '추가 턴': 'Extra Turns',
    '승자': 'Winner',
    '결과 대기': 'Waiting for Result',
    '라운드 결과 저장': 'Save Round Results',
    '내 결과 제출': 'Submit My Result',
    '아직 시작된 라운드가 없습니다.': 'No rounds have started yet.',
    '제출 덱 리스트': 'Submitted Deck Lists',
    '제출 덱 리스트와 캐릭터 분포는 대회 종료 후 공개됩니다.': 'Submitted deck lists and character distribution are shown after the tournament ends.',
    '캐릭터 분포': 'Character Distribution',
    '비공개 덱은 작성자와 대회 운영자에게만 통계에 포함되어 표시됩니다.': 'Private decks are included in stats only for their author and tournament operators.',
    '전체 제출 덱': 'All Submitted Decks',
    '미상': 'Unknown',
    '제출된 덱이 없습니다.': 'No submitted decks.',
    '라운드별 분포': 'Distribution by Round',
    '매칭 데이터가 없습니다.': 'No pairing data.',
    '시작된 라운드가 없습니다.': 'No started rounds.',
    '시간 초과': 'Time Over',
    '내 덱': 'My Deck',
    '라운드 생성 중': 'Creating Round',
    '확인': 'Confirmed',
    '타인의 덱으로 참가 신청하는 경우, 해당 덱이 내 덱으로 복사된 뒤 신청됩니다.': 'When joining with another user’s deck, it will be copied into your decks before submission.',
    '대회 통계': 'Tournament Stats',
    '대회 운영 데이터와 종료된 대회의 덱 제출 데이터를 모아서 확인합니다.': 'Review tournament operations data and deck submission data from finished tournaments.',
    '요약': 'Summary',
    '종료 대회': 'Finished Tournaments',
    '보고된 매치': 'Reported Matches',
    '상태 / 방식': 'Status / Format',
    '태그별 통계': 'Stats by Tag',
    '태그를 선택하면 해당 태그가 붙은 대회만 모아 상세 통계를 확인합니다.': 'Select a tag to view detailed stats for tournaments with that tag.',
    '종료된 대회의 제출 덱을 기준으로 집계합니다.': 'Calculated from submitted decks in finished tournaments.',
    '종료된 대회에서 확인 가능한 제출 덱이 없습니다.': 'No visible submitted decks from finished tournaments.',
    '같은 태그가 붙은 대회들의 운영 결과를 모아서 확인합니다. 덱 제출과 캐릭터 분포는 종료된 대회만 집계합니다.': 'Review operation results for tournaments with the same tag. Deck submissions and character distribution only use finished tournaments.',
    '다른 태그': 'Other Tags',
    '라운드 방식': 'Round Type',
    '아직 진행된 라운드가 없습니다.': 'No rounds have been played yet.',
    '이 태그의 대회가 없습니다.': 'No tournaments with this tag.',
    '남은 시간': 'Time Remaining',
    '대회 상세': 'Tournament Detail',
    '테이블 보드': 'Table Board',
    '테이블 보드는 라운드가 시작된 뒤 표시됩니다.': 'The table board is shown after a round starts.',
    '존재하지 않는 덱입니다.': 'This deck does not exist.',
    '제출할 수 없는 덱입니다.': 'This deck cannot be submitted.',
    '참가 코드가 올바르지 않습니다.': 'The join code is not valid.',
    '요구된 수만큼 덱 리스트를 제출해야 합니다.': 'Submit the required number of deck lists.',
    '같은 덱을 중복 제출할 수 없습니다.': 'The same deck cannot be submitted more than once.',
    '요구 덱 리스트 수는 10개 이하로 설정해주세요.': 'Required deck list count must be 10 or less.',
    '스위스 + 토너먼트 대회는 토너먼트 진출자 수를 2명 이상으로 지정해주세요.': 'Swiss + tournament events require a top cut count of at least 2.',
})

UI_TRANSLATIONS[LANGUAGE_JAPANESE].update({
    '개': '個',
    '종': '種',
    '점': '点',
    '덱 만들기': 'デッキ作成',
    '덱 수정': 'デッキ編集',
    '덱 생성': 'デッキ作成',
    '수정 저장': '変更を保存',
    '덱 이름': 'デッキ名',
    '공개 범위': '公開範囲',
    '덱 설명': 'デッキ説明',
    '덱 설명 열기': 'デッキ説明を開く',
    '덱 설명 닫기': 'デッキ説明を閉じる',
    '카드를 검색해 추가하고, 카드 이미지의 하단 버튼으로 표시 영역을 조정합니다. 버전은 덱의 최신 카드 기준으로 자동 지정됩니다.': 'カードを検索して追加し、カード画像下部のボタンで表示エリアを調整します。バージョンはデッキ内の最新カード基準で自動設定されます。',
    '검색어': '検索語',
    '카드명, 키워드': 'カード名、キーワード',
    '전체': '全体',
    '리스트': 'リスト',
    '손패': '手札',
    '사이드': 'サイド',
    '얼티밋': 'アルティメット',
    '얼티밋 카드': 'アルティメットカード',
    '덱 매수는 최대 {count}장입니다.': 'デッキ枚数は最大{count}枚です。',
    '얼티밋 카드는 1장까지만 넣을 수 있습니다.': 'アルティメットカードは1枚までです。',
    '손패 매수는 최대 5장입니다.': '手札エリアは最大5枚です。',
    '이 카드는 더 넣을 수 없습니다.': 'このカードはこれ以上入れられません。',
    '얼티밋 카드는 얼티밋 영역에 별도로 표시됩니다.': 'アルティメットカードはアルティメットエリアに別表示されます。',
    '키워드, 작성자 검색': 'キーワード、作成者検索',
    '최신순': '新しい順',
    '버전순': 'バージョン順',
    '좋아요순': 'いいね順',
    '덱 검색': 'デッキ検索',
    '덱 이름, 캐릭터, 태그를 바탕으로 덱을 검색합니다.': 'デッキ名、キャラクター、タグでデッキを検索します。',
    '통계': '統計',
    '추천': 'おすすめ',
    '상세 보기': '詳細を見る',
    '텍스트로 보기': 'テキスト表示',
    '이미지로 보기': '画像表示',
    '텍스트 덱 복사': 'テキストデッキコピー',
    '덱 복사': 'デッキコピー',
    '덱 캡쳐': 'デッキキャプチャ',
    '덱 삭제': 'デッキ削除',
    '대회 제출 덱 잠금': '大会提出デッキロック',
    '복사할 덱 리스트가 없습니다.': 'コピーするデッキリストがありません。',
    '클립보드에 복사되었습니다!': 'クリップボードにコピーしました！',
    '이미지 생성 중...': '画像生成中...',
    '컬렉션 카드 추가': 'コレクションカード追加',
    '별도 판본, 스킨, 프로모 수록 정보를 등록합니다.': '別版、スキン、プロモ収録情報を登録します。',
    '연결 카드': 'リンクカード',
    '이미지(webp)': '画像(webp)',
    '팩': 'パック',
    '저장': '保存',
    '저장됨': '保存済み',
    '저장에 실패했습니다.': '保存に失敗しました。',
    '미보유만 보기': '未所持のみ表示',
    '수록 카드, 레어도, 보유 수량을 한 화면에서 확인하고 정리합니다.': '収録カード、レアリティ、所持数を一画面で確認・整理します。',
    '수량을 변경한 뒤 저장 버튼을 눌러주세요. 카드명 또는 코드를 누르면 정렬 기준이 바뀝니다.': '数量を変更したら保存ボタンを押してください。カード名またはコードを押すと並び替え基準が変わります。',
    '이미지': '画像',
    '코드': 'コード',
    '레어도 / 보유': 'レアリティ / 所持',
    '정렬방향': '並び順',
    '미수집 카드만': '未収集カードのみ',
    '이름순': '名前順',
    '코드순': 'コード順',
    '오름차순': '昇順',
    '내림차순': '降順',
    '레어리티': 'レアリティ',
    '검색 키워드 목록': '検索キーワード一覧',
    'N : 노멀': 'N : ノーマル',
    'SR : 슈퍼 레어': 'SR : スーパーレア',
    'EXR : 익스텐드 레어': 'EXR : エクステンドレア',
    'AN : 어나더 노멀': 'AN : アナザーノーマル',
    'AEX : 어나더 익스텐드 레어': 'AEX : アナザーエクステンドレア',
    'SAR : 시크릿 어나더 익스텐드 레어': 'SAR : シークレットアナザーエクステンドレア',
    'SP : 스페셜': 'SP : スペシャル',
    '대회 운영': '大会運営',
    '대회 목록': '大会一覧',
    '대회 검색': '大会検索',
    '대회 상세 본문 영역': '大会詳細本文エリア',
    '라운드': 'ラウンド',
    '상세': '詳細',
    '설정 편집': '設定編集',
    '세츠메이': 'セツメイ',
    '스위스': 'スイス',
    '우승': '優勝',
    '운영자': '運営者',
    '작성자': '作成者',
    '루멘콘덴서 대회를 생성하거나, 대회 목록을 확인합니다.': 'ルーメンコンデンサーの大会を作成したり、大会一覧を確認します。',
    '대회 생성': '大会作成',
    '대회 찾기': '大会検索',
    '전체 상태': '全状態',
    '참가 코드로 참가': '参加コードで参加',
    '참가 코드': '参加コード',
    '일부 공개 대회는 운영자가 공유한 참가 코드나 QR 링크로 입장할 수 있습니다.': '限定公開大会は運営者が共有した参加コードまたはQRリンクで入場できます。',
    '보기': '表示',
    '아직 등록된 대회가 없습니다.': '登録された大会はまだありません。',
    '대회 설명이 없습니다.': '大会説明がありません。',
    '덱 리스트': 'デッキリスト',
    '덱 리스트 미요구': 'デッキリスト不要',
    '스위스 + 토너먼트': 'スイス＋トーナメント',
    '동률': '同率',
    '싱글 엘리미네이션': 'シングルエリミネーション',
    '더블 엘리미네이션': 'ダブルエリミネーション',
    '참가 접수': '参加受付',
    '진행 중': '進行中',
    '종료': '終了',
    '공개': '公開',
    '일부 공개': '限定公開',
    '비공개': '非公開',
    '대회 일시': '大会日時',
    '대회명': '大会名',
    '장소': '場所',
    '운영 방식': '運営方式',
    '토너먼트 방식': 'トーナメント方式',
    '대회 태그': '大会タグ',
    '요구 덱 리스트 수': '要求デッキリスト数',
    '라운드 시간': 'ラウンド時間',
    '라운드 세트 수': 'ラウンドセット数',
    '스위스 라운드 수': 'スイスラウンド数',
    '토너먼트 진출자 수': 'トーナメント進出者数',
    '동률 처리 기준': '同率処理基準',
    '승리 점수': '勝利点',
    '무승부 점수': '引き分け点',
    '패배 점수': '敗北点',
    '최대 참가자': '最大参加者',
    '설명': '説明',
    '비워두면 자동 생성': '空欄なら自動生成',
    '예: 공식/시즌1/입문': '例: 公式/シーズン1/入門',
    '0이면 제한 없음': '0なら制限なし',
    '하이브리드 대회에서 사용': 'ハイブリッド大会で使用',
    '공개 범위, 요구 덱 리스트 수, 기본 라운드 시간과 세트/점수 규칙을 설정합니다. 덱 리스트 수가 0이면 제출을 요구하지 않습니다.': '公開範囲、要求デッキリスト数、基本ラウンド時間とセット/点数ルールを設定します。デッキリスト数が0なら提出不要です。',
    '생성': '作成',
    '대회 설정': '大会設定',
    '대회 진행 중에도 공개 범위, 참가 코드, 라운드 수, 토너먼트 컷, 세트/점수 규칙을 조정할 수 있습니다.': '大会進行中でも公開範囲、参加コード、ラウンド数、トーナメントカット、セット/点数ルールを調整できます。',
    '참가 정보': '参加情報',
    '대회 참가': '大会参加',
    '현재 참가 접수가 닫혀 있습니다.': '現在、参加受付は閉じています。',
    '참가 취소된 상태입니다. 다시 저장하면 참가 상태로 돌아갑니다.': '参加取消状態です。再保存すると参加状態に戻ります。',
    '대회가 시작된 뒤에는 참가 정보와 제출 덱을 수정할 수 없습니다.': '大会開始後は参加情報と提出デッキを修正できません。',
    '표시 이름': '表示名',
    '비워두면 계정 이름 사용': '空欄ならアカウント名を使用',
    '대회 참가 코드를 입력': '大会参加コードを入力',
    '일부 공개 대회는 참가 코드가 있어야 참가 신청이 가능합니다.': '限定公開大会は参加コードが必要です。',
    '이 대회는 덱 리스트': 'この大会はデッキリスト',
    '개 제출이 필요합니다.': '個の提出が必要です。',
    '공개 덱은 유저명이나 덱 이름으로 검색할 수 있고, 일부 공개 덱은 덱 ID를 입력하면 선택할 수 있습니다. 타인의 덱은 내 덱으로 복사된 뒤 제출됩니다.': '公開デッキはユーザー名やデッキ名で検索でき、限定公開デッキはデッキIDを入力して選択できます。他人のデッキは自分のデッキとしてコピーされてから提出されます。',
    '유저명, 덱 이름, 일부 공개 덱 ID': 'ユーザー名、デッキ名、限定公開デッキID',
    '선택된 덱이 없습니다.': '選択されたデッキがありません。',
    '제출 덱': '提出デッキ',
    '참가 정보 저장': '参加情報保存',
    '참가 신청': '参加申請',
    '참가 취소': '参加取消',
    '로그인 후 참가할 수 있습니다.': 'ログイン後に参加できます。',
    '참가 링크': '参加リンク',
    '로 바로 이 대회에 접근할 수 있습니다. QR 이미지는 QR 이미지 열기에서 확인할 수 있습니다.': 'でこの大会に直接アクセスできます。QR画像はQR画像を開くから確認できます。',
    '참가 링크 열기': '参加リンクを開く',
    'QR 이미지 열기': 'QR画像を開く',
    '라운드 시작': 'ラウンド開始',
    '우승자가 결정되어 더 이상 라운드를 생성할 수 없습니다.': '優勝者が決定したため、これ以上ラウンドを生成できません。',
    '매칭 방식': 'マッチング方式',
    '세트 수': 'セット数',
    '일괄 매칭 및 시작': '一括マッチングして開始',
    '대회 종료': '大会終了',
    '이 대회를 삭제할까요? 삭제 후에는 되돌릴 수 없습니다.': 'この大会を削除しますか？削除後は戻せません。',
    '종료되었거나 2라운드 이상 진행된 대회는 슈퍼유저만 삭제할 수 있습니다.': '終了済みまたは2ラウンド以上進行した大会はスーパーユーザーのみ削除できます。',
    '대회 삭제': '大会削除',
    '미종료 테이블 서든 데스': '未終了テーブルをサドンデスへ',
    '아직 종료되지 않은 모든 테이블을 서든 데스로 전환할까요? 각 계산기는 HP 1000, FP 0, 추가 턴 3턴 상태가 됩니다.': '未終了の全テーブルをサドンデスにしますか？各計算機はHP1000、FP0、追加ターン3ターンになります。',
    '순위표': '順位表',
    '참가': '参加',
    '토너먼트 진출': 'トーナメント進出',
    '순위': '順位',
    '참가자': '参加者',
    '덱 제출': 'デッキ提出',
    '점수': '点数',
    '전적': '戦績',
    '비공개 덱': '非公開デッキ',
    '미제출': '未提出',
    '제출': '提出',
    '미요구': '不要',
    '무': '分',
    '패': '敗',
    '무승부': '引き分け',
    '토너먼트 진출 기준선': 'トーナメント進出基準線',
    '아직 참가자가 없습니다.': '参加者がまだいません。',
    '라운드 선택': 'ラウンド選択',
    '계산기 대기': '計算機待機',
    '캐릭터 선택 필요': 'キャラクター選択必要',
    '서든 데스': 'サドンデス',
    '추가 턴': '追加ターン',
    '승자': '勝者',
    '결과 대기': '結果待ち',
    '라운드 결과 저장': 'ラウンド結果保存',
    '내 결과 제출': '自分の結果提出',
    '아직 시작된 라운드가 없습니다.': '開始されたラウンドはまだありません。',
    '제출 덱 리스트': '提出デッキリスト',
    '제출 덱 리스트와 캐릭터 분포는 대회 종료 후 공개됩니다.': '提出デッキリストとキャラクター分布は大会終了後に公開されます。',
    '캐릭터 분포': 'キャラクター分布',
    '비공개 덱은 작성자와 대회 운영자에게만 통계에 포함되어 표시됩니다.': '非公開デッキは作成者と大会運営者にのみ統計へ含めて表示されます。',
    '전체 제출 덱': '全提出デッキ',
    '미상': '不明',
    '제출된 덱이 없습니다.': '提出されたデッキがありません。',
    '라운드별 분포': 'ラウンド別分布',
    '매칭 데이터가 없습니다.': 'マッチングデータがありません。',
    '시작된 라운드가 없습니다.': '開始されたラウンドがありません。',
    '시간 초과': '時間切れ',
    '내 덱': '自分のデッキ',
    '라운드 생성 중': 'ラウンド生成中',
    '확인': '確認',
    '타인의 덱으로 참가 신청하는 경우, 해당 덱이 내 덱으로 복사된 뒤 신청됩니다.': '他人のデッキで参加申請する場合、そのデッキが自分のデッキとしてコピーされてから申請されます。',
    '대회 통계': '大会統計',
    '대회 운영 데이터와 종료된 대회의 덱 제출 데이터를 모아서 확인합니다.': '大会運営データと終了した大会のデッキ提出データをまとめて確認します。',
    '요약': '要約',
    '종료 대회': '終了大会',
    '보고된 매치': '報告済みマッチ',
    '상태 / 방식': '状態 / 方式',
    '태그별 통계': 'タグ別統計',
    '태그를 선택하면 해당 태그가 붙은 대회만 모아 상세 통계를 확인합니다.': 'タグを選択すると、そのタグが付いた大会だけを集めて詳細統計を確認します。',
    '종료된 대회의 제출 덱을 기준으로 집계합니다.': '終了した大会の提出デッキを基準に集計します。',
    '종료된 대회에서 확인 가능한 제출 덱이 없습니다.': '終了した大会で確認可能な提出デッキがありません。',
    '같은 태그가 붙은 대회들의 운영 결과를 모아서 확인합니다. 덱 제출과 캐릭터 분포는 종료된 대회만 집계합니다.': '同じタグが付いた大会の運営結果をまとめて確認します。デッキ提出とキャラクター分布は終了した大会のみ集計します。',
    '다른 태그': '他のタグ',
    '라운드 방식': 'ラウンド方式',
    '아직 진행된 라운드가 없습니다.': '進行済みのラウンドはまだありません。',
    '이 태그의 대회가 없습니다.': 'このタグの大会はありません。',
    '남은 시간': '残り時間',
    '대회 상세': '大会詳細',
    '테이블 보드': 'テーブルボード',
    '테이블 보드는 라운드가 시작된 뒤 표시됩니다.': 'テーブルボードはラウンド開始後に表示されます。',
    '존재하지 않는 덱입니다.': '存在しないデッキです。',
    '제출할 수 없는 덱입니다.': '提出できないデッキです。',
    '참가 코드가 올바르지 않습니다.': '参加コードが正しくありません。',
    '요구된 수만큼 덱 리스트를 제출해야 합니다.': '要求された数のデッキリストを提出してください。',
    '같은 덱을 중복 제출할 수 없습니다.': '同じデッキを重複提出できません。',
    '요구 덱 리스트 수는 10개 이하로 설정해주세요.': '要求デッキリスト数は10個以下に設定してください。',
    '스위스 + 토너먼트 대회는 토너먼트 진출자 수를 2명 이상으로 지정해주세요.': 'スイス＋トーナメント大会はトーナメント進出者数を2名以上に指定してください。',
})


def normalize_language(language):
    if not language:
        return DEFAULT_LANGUAGE
    language = str(language).lower().replace('_', '-')
    language = language.split('-')[0]
    if language in SUPPORTED_LANGUAGE_CODES:
        return language
    return DEFAULT_LANGUAGE


def get_language(request):
    session_language = normalize_language(request.session.get(LANGUAGE_SESSION_KEY))
    if request.session.get(LANGUAGE_SESSION_KEY):
        return session_language

    if getattr(request, 'user', None) and request.user.is_authenticated:
        try:
            return normalize_language(request.user.data.language)
        except Exception:
            pass

    cookie_language = request.COOKIES.get(LANGUAGE_COOKIE_NAME)
    if cookie_language:
        return normalize_language(cookie_language)

    accept_language = request.META.get('HTTP_ACCEPT_LANGUAGE', '')
    if accept_language:
        first_language = accept_language.split(',', 1)[0]
        return normalize_language(first_language)
    return DEFAULT_LANGUAGE


def set_language(request, language):
    language = normalize_language(language)
    request.session[LANGUAGE_SESSION_KEY] = language

    if getattr(request, 'user', None) and request.user.is_authenticated:
        from .models import UserData

        UserData.objects.update_or_create(
            user=request.user,
            defaults={'language': language},
        )
    return language


def language_options(current_language):
    current_language = normalize_language(current_language)
    return [
        {'code': code, 'label': label, 'active': code == current_language}
        for code, label in SUPPORTED_LANGUAGES
    ]


def ui_text(text, language):
    language = normalize_language(language)
    if language == DEFAULT_LANGUAGE:
        return text
    translated = UI_TRANSLATIONS.get(language, {}).get(str(text))
    if translated is not None:
        return translated
    return game_term(text, language)


@lru_cache(maxsize=8)
def custom_term_translations(language):
    language = normalize_language(language)
    if language == DEFAULT_LANGUAGE:
        return {}

    try:
        from .models import TermTranslation

        return dict(
            TermTranslation.objects
            .filter(language=language)
            .values_list('source', 'text')
        )
    except (OperationalError, ProgrammingError):
        return {}


def clear_term_translation_cache():
    custom_term_translations.cache_clear()


def javascript_translations(language):
    language = normalize_language(language)
    if language == DEFAULT_LANGUAGE:
        return {}

    translations = {}
    translations.update(UI_TRANSLATIONS.get(language, {}))
    translations.update(GAME_TERM_TRANSLATIONS.get(language, {}))
    translations.update(PACK_TERM_TRANSLATIONS.get(language, {}))
    translations.update(custom_term_translations(language))
    return translations


def javascript_i18n(language):
    language = normalize_language(language)
    return {
        'language': language,
        'translations': javascript_translations(language),
    }


def _translate_by_parts(text, language, dictionaries):
    if text is None:
        return ''
    language = normalize_language(language)
    if language == DEFAULT_LANGUAGE:
        return text

    text = str(text)
    if text in ('', '-', 'X'):
        return text

    translations = {}
    for dictionary in dictionaries:
        translations.update(dictionary.get(language, {}))
    translations.update(custom_term_translations(language))

    if text in translations:
        return translations[text]

    translated = text
    for source in sorted(translations.keys(), key=len, reverse=True):
        translated = translated.replace(source, translations[source])
    return translated


def game_term(text, language):
    return _translate_by_parts(text, language, [GAME_TERM_TRANSLATIONS, PACK_TERM_TRANSLATIONS])


def translated_choice_label(label, language):
    return ui_text(game_term(label, language), language)


def _prefetched_translations(obj, related_name):
    cache = getattr(obj, '_prefetched_objects_cache', {})
    if related_name in cache:
        return cache[related_name]
    return None


def related_translation(obj, related_name, language):
    language = normalize_language(language)
    if language == DEFAULT_LANGUAGE or obj is None:
        return None

    prefetched = _prefetched_translations(obj, related_name)
    if prefetched is not None:
        for translation in prefetched:
            if translation.language == language:
                return translation
        return None

    manager = getattr(obj, related_name, None)
    if manager is None:
        return None
    try:
        return manager.get(language=language)
    except Exception:
        return None


def translated_field(obj, related_name, language, field_name, fallback=None):
    if obj is None:
        return fallback or ''
    if fallback is None:
        fallback = getattr(obj, field_name, '')

    translation = related_translation(obj, related_name, language)
    if not translation:
        return fallback

    value = getattr(translation, field_name, None)
    if value in (None, ''):
        return fallback
    return value


def translated_card_field(card, language, field_name):
    return translated_field(card, 'translations', language, field_name)


def translated_character_field(character, language, field_name):
    fallback = getattr(character, field_name, '') if character is not None else ''
    if field_name in ('name', 'group'):
        fallback = game_term(fallback, language)
    return translated_field(character, 'translations', language, field_name, fallback=fallback)


def translated_pack_field(pack, language, field_name):
    fallback = getattr(pack, field_name, '')
    fallback = game_term(fallback, language)
    return translated_field(pack, 'translations', language, field_name, fallback=fallback)


def translated_character_datas(character, language):
    base_datas = deepcopy(character.datas or {})
    translation = related_translation(character, 'translations', language)
    if not translation or not translation.datas:
        return base_datas
    translated_datas = deepcopy(translation.datas)
    if not isinstance(translated_datas, dict):
        return base_datas
    base_datas.update(translated_datas)
    return base_datas
