# Generated by Django 5.1.4 on 2025-04-23 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0019_character_icon_img_alter_cardcomment_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most1ed', to='card.card')),
                ('card2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most2ed', to='card.card')),
                ('card3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most3ed', to='card.card')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosted', to='card.character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
