# Generated by Django 5.1.4 on 2026-05-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語')], default='ko', max_length=5),
        ),
    ]
