# Generated by Django 5.1.4 on 2026-05-20 04:00

from django.db import migrations, models


TERM_TRANSLATIONS = [
    ('특성', 'card_type', 'Passive', '特性'),
    ('공격', 'card_type', 'Attack', '攻撃'),
    ('수비', 'card_type', 'Defense', '防御'),
    ('특수', 'card_type', 'Special', '特殊'),
    ('토큰', 'card_type', 'Token', 'トークン'),
    ('얼티밋', 'card_type', 'Ultimate', 'アルティメット'),
    ('상단', 'position', 'High', '上段'),
    ('중단', 'position', 'Mid', '中段'),
    ('하단', 'position', 'Low', '下段'),
    ('손', 'body', 'Hand', '手'),
    ('발', 'body', 'Foot', '足'),
    ('잔향', 'body', 'Echo', '残響'),
    ('방어', 'result', 'Guard', 'ガード'),
    ('회피', 'result', 'Dodge', '回避'),
    ('상쇄', 'result', 'Clash', '相殺'),
    ('산쇄', 'result', 'Clash', '相殺'),
    ('그랩', 'result', 'Grab', '投げ'),
    ('콤보', 'result', 'Combo', 'コンボ'),
    ('히트', 'result', 'Hit', 'ヒット'),
    ('가드', 'result', 'Guard', 'ガード'),
    ('카운터', 'result', 'Counter', 'カウンター'),
    ('상•중•하단 회피', 'special', 'High/Mid/Low Dodge', '上段/中段/下段 回避'),
    ('상단 상쇄', 'special', 'High Clash', '上段 相殺'),
    ('상단 회피', 'special', 'High Dodge', '上段 回避'),
    ('상단·중단 상쇄', 'special', 'High/Mid Clash', '上段/中段 相殺'),
    ('상단·중단 회피', 'special', 'High/Mid Dodge', '上段/中段 回避'),
    ('중단 산쇄', 'special', 'Mid Clash', '中段 相殺'),
    ('중단 상쇄', 'special', 'Mid Clash', '中段 相殺'),
    ('중단 회피', 'special', 'Mid Dodge', '中段 回避'),
    ('하단 상쇄', 'special', 'Low Clash', '下段 相殺'),
    ('하단 회피', 'special', 'Low Dodge', '下段 回避'),
    ('하단 회피/그랩', 'special', 'Low Dodge/Grab', '下段 回避/投げ'),
]


def seed_term_translations(apps, schema_editor):
    TermTranslation = apps.get_model('common', 'TermTranslation')
    rows = []
    for source, category, english, japanese in TERM_TRANSLATIONS:
        rows.append(TermTranslation(source=source, category=category, language='en', text=english))
        rows.append(TermTranslation(source=source, category=category, language='ja', text=japanese))
    TermTranslation.objects.bulk_create(rows, ignore_conflicts=True)


def unseed_term_translations(apps, schema_editor):
    TermTranslation = apps.get_model('common', 'TermTranslation')
    sources = [source for source, _category, _english, _japanese in TERM_TRANSLATIONS]
    TermTranslation.objects.filter(source__in=sources).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_userdata_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', '日本語')], max_length=5)),
                ('text', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('general', '공통'), ('card_type', '카드 분류'), ('position', '위치 판정'), ('body', '부위 판정'), ('special', '특수 판정'), ('result', '판정 결과'), ('tag', '태그'), ('ui', 'UI')], default='general', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['category', 'source', 'language'],
                'verbose_name': '공통 용어 번역',
                'verbose_name_plural': '공통 용어 번역',
                'constraints': [models.UniqueConstraint(fields=('source', 'language'), name='unique_term_translation_language')],
            },
        ),
        migrations.RunPython(seed_term_translations, unseed_term_translations),
    ]
