# Generated by Django 5.1.4 on 2026-08-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_translation_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationsource',
            name='category',
            field=models.CharField(choices=[('card', 'Card'), ('character', 'Character'), ('general', 'General'), ('card_type', 'Card type'), ('position', 'Position'), ('body', 'Body'), ('special', 'Special'), ('result', 'Result'), ('tag', 'Tag'), ('ui', 'UI'), ('pack', 'Pack'), ('keyword', 'Keyword')], default='general', max_length=32),
        ),
    ]
