# Generated by Django 5.1.4 on 2026-08-25 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_rulebooks(apps, schema_editor):
    Rulebook = apps.get_model('common', 'Rulebook')
    RulebookTranslation = apps.get_model('common', 'RulebookTranslation')
    entries = [
        {
            'slug': 'guide',
            'url_name': 'rules:guide',
            'kicker': 'LEARN TO PLAY',
            'visual_file': 'visuals/guide.json',
            'sort_order': 10,
            'searchable': False,
            'title': '루멘콘덴서 처음 플레이 가이드',
            'short_title': '처음 플레이 가이드',
            'summary': '처음 플레이하는 유저가 게임 흐름을 순서대로 익힐 수 있는 가이드입니다.',
        },
        {
            'slug': 'comprehensive',
            'url_name': 'rules:comprehensive',
            'kicker': 'COMPREHENSIVE RULES',
            'visual_file': 'visuals/comprehensive.json',
            'sort_order': 20,
            'searchable': True,
            'title': '루멘콘덴서 종합 규칙서',
            'short_title': '종합 규칙서',
            'summary': '규칙 번호, 딥링크, 판정 확인을 위한 종합 규칙서입니다.',
        },
        {
            'slug': 'tournament',
            'url_name': 'rules:tournament',
            'kicker': 'TOURNAMENT FLOOR RULES',
            'visual_file': 'visuals/tournament.json',
            'sort_order': 30,
            'searchable': True,
            'anchor_prefix': 'floor-',
            'title': '루멘콘덴서 대회 플로어룰',
            'short_title': '대회 플로어룰',
            'summary': '대회 참가자, 관전자, 저지와 운영자를 위한 플로어룰입니다.',
        },
    ]
    for entry in entries:
        rulebook, _created = Rulebook.objects.update_or_create(
            slug=entry['slug'],
            defaults={
                'url_name': entry['url_name'],
                'kicker': entry['kicker'],
                'visual_file': entry['visual_file'],
                'sort_order': entry['sort_order'],
                'searchable': entry['searchable'],
                'anchor_prefix': entry.get('anchor_prefix', 'rule-'),
                'is_public': True,
            },
        )
        RulebookTranslation.objects.update_or_create(
            rulebook=rulebook,
            language='ko',
            defaults={
                'title': entry['title'],
                'short_title': entry['short_title'],
                'summary': entry['summary'],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_reviewed_localization_batch_20260817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rulebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('url_name', models.CharField(blank=True, max_length=80)),
                ('kicker', models.CharField(blank=True, max_length=80)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('visual_file', models.CharField(blank=True, max_length=160)),
                ('searchable', models.BooleanField(default=False)),
                ('anchor_prefix', models.CharField(default='rule-', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '룰북',
                'verbose_name_plural': '룰북',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.SlugField(allow_unicode=True, help_text='다른 규칙에서 [[참조명]]으로 연결할 고유 이름입니다.', max_length=120, unique=True)),
                ('section_code', models.CharField(blank=True, help_text='A.B.C 전체가 아니라 현재 단계의 C만 입력합니다.', max_length=24, validators=[django.core.validators.RegexValidator(message='현재 단계의 번호만 입력하세요. 점(.)은 상위 규칙 경로에서 자동으로 추가됩니다.', regex='^[^.]+$')])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('show_in_toc', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.rule')),
                ('rulebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='common.rulebook')),
            ],
            options={
                'verbose_name': '규칙',
                'verbose_name_plural': '규칙',
                'ordering': ['rulebook__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RulebookTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('rulebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='common.rulebook')),
            ],
            options={
                'verbose_name': '룰북 번역',
                'verbose_name_plural': '룰북 번역',
                'ordering': ['rulebook__sort_order', 'language'],
            },
        ),
        migrations.CreateModel(
            name='RuleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語')], max_length=5)),
                ('title', models.CharField(max_length=240)),
                ('content', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='common.rule')),
            ],
            options={
                'verbose_name': '규칙 번역',
                'verbose_name_plural': '규칙 번역',
                'ordering': ['rule__sort_order', 'language'],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['rulebook', 'parent', 'sort_order'], name='common_rule_ruleboo_52edd5_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['rulebook', 'is_public'], name='common_rule_ruleboo_e39640_idx'),
        ),
        migrations.AddConstraint(
            model_name='rulebooktranslation',
            constraint=models.UniqueConstraint(fields=('rulebook', 'language'), name='unique_rulebook_translation_language'),
        ),
        migrations.AddConstraint(
            model_name='ruletranslation',
            constraint=models.UniqueConstraint(fields=('rule', 'language'), name='unique_rule_translation_language'),
        ),
        migrations.RunPython(seed_rulebooks, migrations.RunPython.noop),
    ]
