# Generated by Django 5.1.4 on 2026-08-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_rulebook_rule_rulebooktranslation_ruletranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='reference_aliases',
            field=models.JSONField(blank=True, default=list, help_text='참조명 변경 전 딥링크를 유지하기 위한 이전 참조명입니다.'),
        ),
    ]
