# Generated by Django 5.1.4 on 2026-09-01 12:00

import re
from datetime import date

from django.db import migrations, models


LANGUAGES = ('ko', 'en', 'ja')
REFERENCE_TOKEN_RE = re.compile(r'\[\[([^\[\]]+?)\]\]')

SECTION_TITLES = {
    'ko': '규칙 객체와 참조 계약',
    'en': 'Rule Objects and Reference Contracts',
    'ja': '規則オブジェクトと参照契約',
}

CONTRACT_RULES = (
    (
        'rule-contract-unit',
        {'ko': '규칙 객체', 'en': 'Rule Object', 'ja': '規則オブジェクト'},
        {
            'ko': '각 규칙은 하나의 독립된 <strong>규칙 객체</strong>다. 규칙 객체는 참조 키, 상위 규칙, 규범 본문과 참조 규칙을 가진다. 규범 본문은 적용 대상, 전제조건, 수행할 처리, 처리 결과와 예외 중 해당하는 항목을 명시하며, 명시하지 않은 조건·결과·예외를 임의로 보충하지 않는다.',
            'en': 'Each rule is an independent <strong>rule object</strong>. A rule object has a reference key, a parent rule, normative text, and referenced rules. Its normative text states each applicable subject, precondition, operation, result, and exception; no unstated condition, result, or exception is inferred.',
            'ja': '各規則は独立した<strong>規則オブジェクト</strong>である。規則オブジェクトは参照キー、上位規則、規範本文、参照規則を持つ。規範本文は、該当する適用対象、前提条件、実行する処理、処理結果、例外を明示し、明示されていない条件・結果・例外を任意に補わない。',
        },
    ),
    (
        'rule-reference-key',
        {'ko': '참조 키', 'en': 'Reference Key', 'ja': '参照キー'},
        {
            'ko': '<strong>참조 키</strong>는 규칙 객체를 식별하는 유일하고 지속적인 문자열이다. 참조 키는 <code>rule-...</code> 형식을 사용하며 같은 키를 둘 이상의 규칙에 부여할 수 없다. 표시 번호나 배치가 바뀌어도 참조 키의 의미는 바뀌지 않으며, 변경 전 키는 같은 규칙의 별칭으로 보존한다.',
            'en': 'A <strong>reference key</strong> is a unique, persistent string identifying one rule object. It uses the <code>rule-...</code> form, and no two rules may share a key. A layout or display-number change does not change the key\'s meaning; an earlier key is retained as an alias of the same rule.',
            'ja': '<strong>参照キー</strong>は1つの規則オブジェクトを識別する一意かつ永続的な文字列である。<code>rule-...</code>形式を用い、2つ以上の規則に同じキーを付与できない。配置や表示番号が変わってもキーの意味は変わらず、変更前のキーは同じ規則の別名として保持する。',
        },
    ),
    (
        'rule-scope-inheritance',
        {'ko': '상위 범위의 상속', 'en': 'Parent-Scope Inheritance', 'ja': '上位範囲の継承'},
        {
            'ko': '하위 규칙은 상위 규칙이 정한 정의와 적용 범위를 상속한다. 하위 규칙이 상위 규칙의 일부를 명시적으로 제한하거나 예외로 선언하면 그 범위에서 하위 규칙을 우선하고, 명시적으로 변경하지 않은 부분은 상위 규칙과 함께 적용한다. 한 규칙의 하위 규칙은 다른 형제 규칙의 범위를 자동으로 변경하지 않는다.',
            'en': 'A child rule inherits the definitions and scope established by its parent. If a child expressly restricts or declares an exception to part of its parent, the child governs that part; everything not expressly changed applies together with the parent. A child of one rule does not automatically change the scope of a sibling rule.',
            'ja': '下位規則は上位規則が定めた定義と適用範囲を継承する。下位規則が上位規則の一部を明示的に制限し、または例外として宣言した場合、その範囲では下位規則を優先し、明示的に変更していない部分は上位規則とともに適用する。ある規則の下位規則は、別の兄弟規則の範囲を自動的に変更しない。',
        },
    ),
    (
        'rule-dependency-resolution',
        {'ko': '참조 규칙의 처리', 'en': 'Resolving Referenced Rules', 'ja': '参照規則の処理'},
        {
            'ko': '규칙 객체가 다른 규칙을 참조하면 참조된 규칙의 정의·조건·절차를 다시 적지 않고 그대로 사용한다. 절차 처리 중 다른 절차를 참조하면 참조된 절차를 완료한 뒤 호출한 규칙의 다음 처리로 돌아간다. 단순한 상호 참조는 처리의 반복을 발생시키지 않으며, 반복은 규칙이 재실행 조건과 종료 조건을 명시한 경우에만 수행한다.',
            'en': 'When a rule object references another rule, it uses the referenced rule\'s definitions, conditions, and procedure without restating them. If a procedure references another procedure while resolving, complete the referenced procedure and then resume with the caller\'s next operation. A mutual semantic reference does not itself cause repeated processing; repetition occurs only when a rule states both a repeat condition and a termination condition.',
            'ja': '規則オブジェクトが別の規則を参照する場合、参照先の定義・条件・手順を再記述せずそのまま使用する。手順の処理中に別の手順を参照した場合、参照先の手順を完了してから呼出元の次の処理へ戻る。単純な相互参照だけでは処理を反復せず、反復条件と終了条件の両方を規則が明示した場合にのみ反復する。',
        },
    ),
    (
        'rule-normative-clause-contract',
        {'ko': '규범 문장의 처리', 'en': 'Normative Clause Contract', 'ja': '規範文の処理'},
        {
            'ko': '조건부 규칙은 조건이 참일 때만 지시된 처리를 수행한다. “한다”는 의무 처리이고 “할 수 있다”는 선택 처리이며, 처리 결과는 해당 문장이 정한 범위에서만 게임 상태를 변경한다. 예외는 적용 대상과 대체할 처리를 명시해야 하며, 예외가 끝난 뒤에는 변경되지 않은 일반 규칙을 계속 적용한다.',
            'en': 'A conditional rule performs its instructed operation only when its condition is true. “Do” is mandatory and “may” is optional, and a result changes game state only within the scope stated by that sentence. An exception must identify its subject and replacement operation; after the exception ends, every unchanged general rule continues to apply.',
            'ja': '条件付き規則は条件が真の場合にのみ指示された処理を行う。「行う」は必須処理、「できる」は選択処理であり、処理結果はその文が定めた範囲でのみゲーム状態を変更する。例外は適用対象と置換する処理を明示し、例外の終了後は変更されていない一般規則を引き続き適用する。',
        },
    ),
)

REVISION_CONTENT = {
    'ko': '''<table><thead><tr><th>버전</th><th>기준일</th><th>주요 내용</th><th>상태</th></tr></thead><tbody>
<tr><td>v0.6-web</td><td>2026-09-01</td><td>모든 규칙에 객체 계약·참조 키·상위 범위·규칙 간 의존 관계와 참조 무결성 검사를 추가</td><td>검토 초안</td></tr>
<tr><td>v0.5-web</td><td>2026-09-01</td><td>게임 객체를 플레이어·카드로 재정의하고 객체별 정보와 조항 표시 방식 정리</td><td>검토 초안</td></tr>
<tr><td>v0.4-web</td><td>2026-09-01</td><td>각 게임 영역의 용도·귀속·공개 상태·매수 제한·이동 예외 상세화</td><td>검토 초안</td></tr>
<tr><td>v0.3-web</td><td>2026-09-01</td><td>종합 규칙서의 장 구성과 배치 순서 재정리</td><td>검토 초안</td></tr>
<tr><td>v0.1</td><td>2026-08-13</td><td>기존 룰북의 규칙 인벤토리와 공식 결정 65개 통합</td><td>검토 초안</td></tr>
<tr><td>v0.1-web</td><td>2026-08-24</td><td>웹 편집용 Markdown, 안정적 규칙 앵커와 시각화 지시 추가</td><td>검토 초안</td></tr>
</tbody></table>''',
    'en': '''<table><thead><tr><th>Version</th><th>Date</th><th>Highlights</th><th>Status</th></tr></thead><tbody>
<tr><td>v0.6-web</td><td>2026-09-01</td><td>Added rule-object contracts, reference keys, parent scope, inter-rule dependencies, and reference-integrity validation</td><td>Review draft</td></tr>
<tr><td>v0.5-web</td><td>2026-09-01</td><td>Redefined game objects as players and cards, detailed their information, and simplified clause display</td><td>Review draft</td></tr>
<tr><td>v0.4-web</td><td>2026-09-01</td><td>Expanded every game area's purpose, player association, visibility, capacity, and movement exceptions</td><td>Review draft</td></tr>
<tr><td>v0.3-web</td><td>2026-09-01</td><td>Reorganized the chapter structure and reading order of the Comprehensive Rules</td><td>Review draft</td></tr>
<tr><td>v0.1</td><td>2026-08-13</td><td>Integrated the existing rule inventory and 65 official ruling answers</td><td>Review draft</td></tr>
<tr><td>v0.1-web</td><td>2026-08-24</td><td>Added web-editing Markdown, stable rule anchors, and visualization instructions</td><td>Review draft</td></tr>
</tbody></table>''',
    'ja': '''<table><thead><tr><th>バージョン</th><th>基準日</th><th>主な内容</th><th>状態</th></tr></thead><tbody>
<tr><td>v0.6-web</td><td>2026-09-01</td><td>全規則にオブジェクト契約・参照キー・上位範囲・規則間依存関係・参照整合性検査を追加</td><td>レビュードラフト</td></tr>
<tr><td>v0.5-web</td><td>2026-09-01</td><td>ゲームオブジェクトをプレイヤーとカードに再定義し、オブジェクト別情報と条項表示を整理</td><td>レビュードラフト</td></tr>
<tr><td>v0.4-web</td><td>2026-09-01</td><td>各ゲーム領域の用途・プレイヤーとの対応・公開状態・枚数上限・移動例外を詳細化</td><td>レビュードラフト</td></tr>
<tr><td>v0.3-web</td><td>2026-09-01</td><td>総合ルールの章構成と配置順を再整理</td><td>レビュードラフト</td></tr>
<tr><td>v0.1</td><td>2026-08-13</td><td>既存ルールブックのルール一覧と65件の公式裁定を統合</td><td>レビュードラフト</td></tr>
<tr><td>v0.1-web</td><td>2026-08-24</td><td>ウェブ編集用Markdown、安定したルールアンカー、可視化指示を追加</td><td>レビュードラフト</td></tr>
</tbody></table>''',
}


def _alias_map(rules):
    return {
        key: rule
        for rule in rules
        for key in [rule.reference_name, *(rule.reference_aliases or [])]
        if key
    }


def _unique_reference(Rule, reference):
    candidate = reference
    index = 2
    while Rule.objects.filter(reference_name=candidate).exists():
        candidate = f'{reference}-{index}'
        index += 1
    return candidate


def _set_translation(RuleTranslation, rule, titles, contents):
    for language in LANGUAGES:
        RuleTranslation.objects.update_or_create(
            rule_id=rule.pk,
            language=language,
            defaults={
                'title': titles[language],
                'content': f'<p>{contents[language]}</p>',
            },
        )


def _rule_table_columns(schema_editor, Rule):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor,
            Rule._meta.db_table,
        )
    return {column.name for column in description}


def ensure_reference_targets_column(apps, schema_editor):
    """Add the column on a fresh DB and tolerate a retry after MySQL DDL committed."""
    Rule = apps.get_model('common', 'Rule')
    if 'reference_targets' in _rule_table_columns(schema_editor, Rule):
        return
    schema_editor.add_field(Rule, Rule._meta.get_field('reference_targets'))


def remove_reference_targets_column(apps, schema_editor):
    Rule = apps.get_model('common', 'Rule')
    if 'reference_targets' not in _rule_table_columns(schema_editor, Rule):
        return
    schema_editor.remove_field(Rule, Rule._meta.get_field('reference_targets'))


def add_rule_contract_references(apps, schema_editor):
    from common.rule_contracts import COMPREHENSIVE_RULE_DEPENDENCIES

    Rulebook = apps.get_model('common', 'Rulebook')
    Rule = apps.get_model('common', 'Rule')
    RuleTranslation = apps.get_model('common', 'RuleTranslation')

    try:
        book = Rulebook.objects.get(slug='comprehensive')
    except Rulebook.DoesNotExist:
        return
    rules = list(Rule.objects.filter(rulebook_id=book.pk).order_by('priority', 'pk'))
    if not rules:
        return
    aliases = _alias_map(rules)
    root = aliases.get('chapter-0')
    if root is None:
        return

    section = aliases.get('rule-rule-contracts')
    if section is None:
        reference = _unique_reference(Rule, 'rule-rule-contracts')
        section = Rule.objects.create(
            rulebook_id=book.pk,
            parent_id=root.pk,
            reference_name=reference,
            reference_aliases=[] if reference == 'rule-rule-contracts' else ['rule-rule-contracts'],
            reference_targets=[],
            priority=30,
            show_in_toc=True,
            is_public=True,
        )
    for language in LANGUAGES:
        RuleTranslation.objects.update_or_create(
            rule_id=section.pk,
            language=language,
            defaults={'title': SECTION_TITLES[language], 'content': ''},
        )

    for priority, (reference_key, titles, contents) in enumerate(CONTRACT_RULES, start=1):
        rules = list(Rule.objects.filter(rulebook_id=book.pk))
        aliases = _alias_map(rules)
        rule = aliases.get(reference_key)
        if rule is None:
            reference = _unique_reference(Rule, reference_key)
            rule = Rule.objects.create(
                rulebook_id=book.pk,
                parent_id=section.pk,
                reference_name=reference,
                reference_aliases=[] if reference == reference_key else [reference_key],
                reference_targets=[],
                priority=priority * 10,
                show_in_toc=False,
                is_public=True,
            )
        else:
            rule.parent_id = section.pk
            rule.priority = priority * 10
            rule.show_in_toc = False
            rule.is_public = True
            rule.save(update_fields=['parent', 'priority', 'show_in_toc', 'is_public'])
        _set_translation(RuleTranslation, rule, titles, contents)

    rules = list(
        Rule.objects
        .filter(rulebook_id=book.pk)
        .prefetch_related('translations')
    )
    aliases = _alias_map(rules)
    # A comprehensive rule may deliberately refer to a floor/tournament rule.
    # Resolve dependency targets globally while keeping dependency sources scoped
    # to this rulebook.
    all_aliases = _alias_map(Rule.objects.all())
    missing_targets = sorted({
        reference
        for references in COMPREHENSIVE_RULE_DEPENDENCIES.values()
        for reference in references
        if reference not in all_aliases
    })
    if missing_targets:
        raise RuntimeError(
            '종합 규칙서 규칙 계약이 존재하지 않는 참조 키를 사용합니다: '
            + ', '.join(missing_targets)
        )

    for rule in rules:
        configured = []
        for key in [rule.reference_name, *(rule.reference_aliases or [])]:
            if key in COMPREHENSIVE_RULE_DEPENDENCIES:
                configured.extend(COMPREHENSIVE_RULE_DEPENDENCIES[key])
                break
        for translation in rule.translations.all():
            for match in REFERENCE_TOKEN_RE.finditer(translation.content or ''):
                reference = match.group(1).partition('|')[0].strip()
                if reference.startswith(('rule-', 'floor-')):
                    configured.append(reference)
        targets = []
        for reference in configured:
            target = all_aliases.get(reference)
            if target is None:
                raise RuntimeError(
                    f'{rule.reference_name} 규칙이 존재하지 않는 {reference} 키를 참조합니다.'
                )
            if target.pk != rule.pk and target.reference_name not in targets:
                targets.append(target.reference_name)
        if targets != (rule.reference_targets or []):
            rule.reference_targets = targets
            rule.save(update_fields=['reference_targets'])

    appendix_t = aliases.get('appendix-t')
    if appendix_t is not None:
        revision = (
            Rule.objects
            .filter(
                rulebook_id=book.pk,
                parent_id=None,
                priority__gt=appendix_t.priority,
            )
            .order_by('priority', 'pk')
            .first()
        )
        if revision is not None:
            for language in LANGUAGES:
                RuleTranslation.objects.update_or_create(
                    rule_id=revision.pk,
                    language=language,
                    defaults={
                        'title': {
                            'ko': '개정 이력',
                            'en': 'Revision History',
                            'ja': '改訂履歴',
                        }[language],
                        'content': REVISION_CONTENT[language],
                    },
                )

    book.version = '0.6-web'
    book.updated_on = date(2026, 9, 1)
    book.save(update_fields=['version', 'updated_on'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_restructure_game_objects'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='rule',
                    name='reference_targets',
                    field=models.JSONField(blank=True, default=list, help_text='이 규칙이 정의·절차·예외를 가져와 사용하는 다른 규칙의 참조명 목록입니다. 예: ["rule-processing-unit", "rule-priority"]'),
                ),
            ],
        ),
        migrations.RunPython(
            ensure_reference_targets_column,
            remove_reference_targets_column,
        ),
        migrations.RunPython(add_rule_contract_references, migrations.RunPython.noop),
    ]
