# Generated by Django 5.1.4 on 2025-04-03 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_body_alter_card_character_alter_card_code_and_more'),
        ('collection', '0002_alter_collected_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collected',
            name='card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='collected', to='collection.collectioncard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectioncard',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection_card', to='card.card'),
        ),
    ]
