# Generated by Django 5.1.4 on 2025-04-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collected_card_alter_collectioncard_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncard',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
