# Generated by Django 5.1.4 on 2025-04-04 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_collectioncard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncard',
            name='released',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 20), null=True),
        ),
    ]
