# Generated by Django 5.1.4 on 2025-04-04 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collectioncard_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=20)),
                ('released', models.DateField(blank=True, default=datetime.date(2024, 2, 20), null=True)),
            ],
        ),
    ]
