# Generated by Django 5.1.4 on 2025-04-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioncard',
            name='released',
        ),
        migrations.AddField(
            model_name='collectioncard',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection_card', to='collection.pack'),
        ),
    ]
