# Generated by Django 5.1.4 on 2025-04-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_collectioncard_released_collectioncard_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncard',
            name='img_sm',
            field=models.URLField(blank=True, default=''),
        ),
    ]
