# Generated by Django 5.1.4 on 2026-05-20 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_collectioncard_img_sm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', '日本語')], max_length=5)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='collection.pack')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pack', 'language'), name='unique_pack_translation_language')],
            },
        ),
    ]
