# Generated by Django 5.1.4 on 2026-10-09 03:30

from django.conf import settings
from django.db import migrations, models


def preserve_duplicates(apps, schema_editor):
    Collected = apps.get_model('collection', 'Collected')
    Archive = apps.get_model('collection', 'CollectedDuplicateArchive')
    alias = schema_editor.connection.alias
    duplicates = Collected.objects.using(alias).values('user_id', 'card_id').annotate(total=models.Count('id')).filter(total__gt=1)
    for group in duplicates.iterator():
        rows = list(Collected.objects.using(alias).filter(user_id=group['user_id'], card_id=group['card_id']).order_by('-id'))
        Archive.objects.using(alias).bulk_create([Archive(original_id=r.pk, user_id_value=r.user_id, card_id_value=r.card_id, amount=r.amount) for r in rows])
        Collected.objects.using(alias).filter(pk__in=[r.pk for r in rows[1:]]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_collectioncard_character_item_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedDuplicateArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.BigIntegerField()),
                ('user_id_value', models.BigIntegerField()),
                ('card_id_value', models.BigIntegerField()),
                ('amount', models.SmallIntegerField()),
            ],
        ),
        migrations.RunPython(preserve_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='collected',
            constraint=models.UniqueConstraint(fields=('user', 'card'), name='collection_user_card_unique'),
        ),
    ]
