# Generated by Django 5.1.4 on 2025-02-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('group', models.CharField(max_length=100)),
                ('hp_hand', models.JSONField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ruby', models.CharField(blank=True, max_length=100)),
                ('frame', models.SmallIntegerField(null=True)),
                ('damage', models.IntegerField(null=True)),
                ('pos', models.CharField(max_length=3, null=True)),
                ('body', models.CharField(default='', max_length=10, null=True)),
                ('text', models.TextField(blank=True)),
                ('hit', models.CharField(default=0, max_length=4, null=True)),
                ('guard', models.CharField(default=0, max_length=4, null=True)),
                ('counter', models.CharField(default=0, max_length=4, null=True)),
                ('special', models.CharField(blank=True, max_length=20, null=True)),
                ('g_top', models.CharField(blank=True, max_length=5, null=True)),
                ('g_mid', models.CharField(blank=True, max_length=5, null=True)),
                ('g_bot', models.CharField(blank=True, max_length=5, null=True)),
                ('type', models.CharField(default='공격', max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('img', models.URLField()),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('search', models.CharField(blank=True, default='', max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='card.character')),
            ],
        ),
    ]
