# Generated by Django 5.1.3 on 2024-11-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('group', models.CharField(max_length=100)),
                ('hp_hand', models.JSONField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ruby', models.CharField(max_length=100)),
                ('frame', models.SmallIntegerField()),
                ('damage', models.IntegerField()),
                ('pos', models.CharField(max_length=3)),
                ('body', models.CharField(max_length=10, null=True)),
                ('text', models.TextField(blank=True)),
                ('type', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('img', models.URLField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='card.character')),
            ],
        ),
    ]
