# Generated by Django 5.1.4 on 2025-02-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'permissions': [('tag_update', '태그 수정')]},
        ),
    ]
