# Generated by Django 5.1.4 on 2024-12-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='g_bot',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='card',
            name='g_mid',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='card',
            name='g_top',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='card',
            name='guard',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='hit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='special',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(default='공격', max_length=10),
        ),
    ]
