# Generated by Django 5.1.4 on 2024-12-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_counter_card_g_bot_card_g_mid_card_g_top_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='body',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='ruby',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
