# Generated by Django 5.1.4 on 2024-12-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_body_alter_card_ruby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='frame',
            field=models.SmallIntegerField(null=True),
        ),
    ]
