# Generated by Django 5.1.4 on 2025-02-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
