# Generated by Django 5.1.4 on 2024-12-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='damage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='pos',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
