# Generated by Django 5.1.4 on 2025-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='hiddenKeyword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
