# Generated by Django 5.1.4 on 2024-12-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_card_damage_alter_card_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='body',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='g_bot',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='g_mid',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='g_top',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='special',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
