# Generated by Django 5.1.4 on 2024-12-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_body_alter_card_g_bot_alter_card_g_mid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='counter',
            field=models.CharField(default=0, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='guard',
            field=models.CharField(default=0, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='hit',
            field=models.CharField(default=0, max_length=4, null=True),
        ),
    ]
