# Generated by Django 5.1.4 on 2025-04-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_body_alter_card_character_alter_card_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img_sm',
            field=models.URLField(blank=True, default=''),
        ),
    ]
