# Generated by Django 5.1.4 on 2025-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_card_img_sm'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img_mid',
            field=models.URLField(blank=True, default=''),
        ),
    ]
