# Generated by Django 5.1.4 on 2024-12-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_card_counter_alter_card_guard_alter_card_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
