# Generated by Django 5.1.4 on 2025-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_card_img_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(default='#ffffff', max_length=12),
        ),
    ]
