# Generated by Django 5.1.4 on 2024-12-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_card_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='search',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
