# Generated by Django 5.1.4 on 2024-12-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_card_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='body',
            field=models.CharField(default='', max_length=10),
        ),
    ]
