# Generated by Django 5.1.4 on 2025-01-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_alter_card_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='g_bot',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='g_mid',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='g_top',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='special',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
