# Generated by Django 5.1.4 on 2025-04-18 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_cardcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
