# Generated by Django 5.1.4 on 2025-04-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_cardcomment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcomment',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
