# Generated by Django 5.1.4 on 2025-04-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_cardcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcomment',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
