# Generated by Django 5.1.4 on 2025-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_alter_cardcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcomment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
