# Generated by Django 5.1.4 on 2025-04-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_alter_cardcomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sd_img',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
