# Generated by Django 5.1.4 on 2025-04-18 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_character_sd_img'),
        ('collection', '0008_collectioncard_img_sm'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pack',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.pack'),
        ),
    ]
