# Generated by Django 5.1.4 on 2025-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_character_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='datas',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
