# Generated by Django 5.1.4 on 2025-05-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0019_character_icon_img_alter_cardcomment_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('power', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('combo', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('reversal', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('safety', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('tempo', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.character')),
            ],
        ),
    ]
