# Generated by Django 5.1.4 on 2025-07-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0020_charactercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ultimate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
