# Generated by Django 5.1.4 on 2026-05-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0021_card_ultimate_alter_card_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='body_img',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
