# Generated by Django 5.1.4 on 2026-05-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0022_character_body_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='detail_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
