# Generated by Django 5.1.4 on 2026-05-20 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0023_card_detail_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', '日本語')], max_length=5)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ruby', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('detail_text', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('hiddenKeyword', models.CharField(blank=True, default='', max_length=255)),
                ('search', models.CharField(blank=True, default='', max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='card.card')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'language'), name='unique_card_translation_language')],
            },
        ),
        migrations.CreateModel(
            name='CharacterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', '日本語')], max_length=5)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('datas', models.JSONField(blank=True, default=dict)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='card.character')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'language'), name='unique_character_translation_language')],
            },
        ),
    ]
