# Generated by Django 5.1.4 on 2026-08-17

import card.models
from django.db import migrations, models
from django.utils import timezone


def mark_textless_cards_reviewed(apps, schema_editor):
    Card = apps.get_model('card', 'Card')
    Card.objects.filter(effect_updated_at__isnull=True).update(effect_updated_at=timezone.now())
    Card.objects.filter(text='').update(effect_definition={
        'schema_version': 1,
        'reviewed': True,
        'no_effect': True,
        'source_refs': {'rulebook_pages': [], 'qna_ids': []},
        'abilities': [],
    })


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0025_localization_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='effect_definition',
            field=models.JSONField(blank=True, default=card.models.default_effect_definition),
        ),
        migrations.AddField(
            model_name='card',
            name='effect_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='effect_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(mark_textless_cards_reviewed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='card',
            name='effect_updated_at',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
