# Generated by Django 5.1.4 on 2024-12-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardindeck',
            name='hand',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cardindeck',
            name='side',
            field=models.SmallIntegerField(default=1),
        ),
    ]
