# Generated by Django 5.1.4 on 2025-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
