# Generated by Django 5.1.4 on 2025-01-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_cardindeck_hand_cardindeck_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardindeck',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deck',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
