# Generated by Django 5.1.4 on 2025-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_deck_private_deck_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
