# Generated by Django 5.1.4 on 2025-04-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_deckcomment_decklike'),
    ]

    operations = [
        migrations.AddField(
            model_name='decklike',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decklike',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
