# Generated by Django 5.1.4 on 2025-01-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_deck_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardindeck',
            name='description',
        ),
        migrations.AlterField(
            model_name='cardindeck',
            name='hand',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardindeck',
            name='side',
            field=models.SmallIntegerField(default=0),
        ),
    ]
