# Generated by Django 5.1.4 on 2025-04-14 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0005_decklike_bookmark_decklike_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deckcomment',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_comment', to='deck.deck'),
        ),
        migrations.AlterField(
            model_name='decklike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decklike',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_like', to='deck.deck'),
        ),
    ]
