# Generated by Django 5.1.4 on 2025-04-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_card_img_mid'),
        ('deck', '0006_alter_deckcomment_author_alter_deckcomment_deck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='card.character'),
        ),
    ]
