# Generated by Django 5.1.4 on 2025-04-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_cardcomment'),
        ('deck', '0007_alter_deck_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardindeck',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cids', to='card.card'),
        ),
        migrations.AlterField(
            model_name='cardindeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cids', to='deck.deck'),
        ),
    ]
