# Generated by Django 5.1.4 on 2025-05-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0009_alter_deck_author_alter_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
