# Generated by Django 5.1.4 on 2026-05-09 13:15

from django.db import migrations, models


def migrate_deck_visibility(apps, schema_editor):
    Deck = apps.get_model('deck', 'Deck')
    Deck.objects.filter(private=True).update(visibility='private')
    Deck.objects.filter(private=False).update(visibility='public')


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0010_deck_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='visibility',
            field=models.CharField(choices=[('public', '공개'), ('unlisted', '일부 공개'), ('private', '비공개')], default='public', max_length=12),
        ),
        migrations.RunPython(migrate_deck_visibility, migrations.RunPython.noop),
    ]
