# Generated by Django 5.1.4 on 2026-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0011_deck_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
