# Generated by Django 5.1.4 on 2026-05-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0012_alter_deck_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='version',
            field=models.CharField(default='LMI', max_length=20),
        ),
    ]
