# Generated by Django 5.1.4 on 2026-10-09 03:30

import uuid
from django.db import migrations, models


def fill_ids(apps, schema_editor):
    Deck = apps.get_model('deck', 'Deck')
    for deck in Deck.objects.using(schema_editor.connection.alias).all().iterator():
        Deck.objects.using(schema_editor.connection.alias).filter(pk=deck.pk).update(mobile_id=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0013_alter_deck_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='mobile_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(fill_ids, migrations.RunPython.noop),
        migrations.AlterField(model_name='deck', name='mobile_id', field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
    ]
